export interface Lesson {
  id: string;
  title: string;
  content: string;
  videoUrl?: string;
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
}

export interface Module {
  id: number;
  title: string;
  section: string;
  description: string;
  tier: "free" | "premium";
  lessons: Lesson[];
  quiz: QuizQuestion[];
}

export const SECTIONS = [
  { name: "Section I: AI Foundations", modules: [1, 2, 3, 4], tier: "free" as const },
  { name: "Section II: Essential AI Tools", modules: [5, 6, 7, 8], tier: "free" as const },
  { name: "Section III: Real Estate AI Workflows", modules: [9, 10, 11, 12], tier: "premium" as const },
  { name: "Section IV: Advanced AI Strategies", modules: [13, 14, 15, 16], tier: "premium" as const },
  { name: "Section V: Certification", modules: [17], tier: "premium" as const },
];

export const MODULES: Module[] = [
  {
    id: 1, title: "What is AI? A Realtor's Guide", section: "AI Foundations", tier: "free",
    description: "Understand what AI really is, how it works in simple terms, and why it matters for your real estate business.",
    lessons: [
      { id: "1-1", title: "AI Demystified: What It Actually Is", content: "Artificial Intelligence isn't the sci-fi robots you see in movies. For realtors, AI is simply software that can learn patterns and make predictions. Think of it as a very smart assistant that gets better the more you use it.\n\nAt its core, AI works by analyzing huge amounts of data to find patterns. When you use AI for real estate, it's drawing on millions of examples of property descriptions, market data, client communications, and more to help you work faster and smarter.\n\n**Key Takeaway:** AI is a tool, not a replacement. The best realtors will be those who learn to use AI as a force multiplier for their expertise." },
      { id: "1-2", title: "How AI Applies to Real Estate", content: "AI touches every part of the real estate transaction cycle. Here are the key areas where AI is already making an impact:\n\n**Listing Descriptions:** Generate compelling, accurate property descriptions in seconds instead of hours.\n\n**Client Communications:** Draft personalized emails, follow-ups, and market updates that sound like you wrote them.\n\n**Market Analysis:** Analyze comparable sales, market trends, and pricing data faster than any human could.\n\n**Marketing:** Create social media posts, email campaigns, and advertising copy tailored to your brand.\n\n**Transaction Management:** Track timelines, generate checklists, and stay on top of every detail." },
      { id: "1-3", title: "The AI Advantage: Why Early Adopters Win", content: "The real estate industry is at a tipping point. Agents who adopt AI now will have a significant competitive advantage:\n\n**Time Savings:** AI can reduce administrative tasks by 60-70%, freeing you to focus on relationships and closings.\n\n**Consistency:** AI helps maintain consistent quality in all your communications and marketing.\n\n**Scale:** Handle more clients without sacrificing quality. AI lets a solo agent operate like a team.\n\n**Speed:** Respond to leads in minutes instead of hours. First response time is the #1 predictor of lead conversion.\n\nThe agents who master AI in 2026 will be the market leaders of 2027 and beyond." },
    ],
    quiz: [
      { question: "What is the best description of AI for real estate agents?", options: ["A robot that replaces agents", "Software that learns patterns to help you work smarter", "A database of property listings", "An automated phone system"], correct: 1 },
      { question: "Which area does AI NOT directly help with in real estate?", options: ["Writing listing descriptions", "Physically showing homes to buyers", "Creating marketing materials", "Analyzing market data"], correct: 1 },
      { question: "What is the #1 predictor of lead conversion?", options: ["Price of the property", "Agent's years of experience", "First response time", "Number of photos in listing"], correct: 2 },
      { question: "By how much can AI reduce administrative tasks?", options: ["10-20%", "30-40%", "60-70%", "90-100%"], correct: 2 },
      { question: "What is the best way to think about AI as a realtor?", options: ["It will replace my job", "It's a force multiplier for my expertise", "It's only for tech-savvy agents", "It's a passing trend"], correct: 1 },
    ]
  },
  {
    id: 2, title: "Setting Up Your AI Toolkit", section: "AI Foundations", tier: "free",
    description: "Get hands-on with the essential AI tools every realtor needs, starting with ChatGPT and Claude.",
    lessons: [
      { id: "2-1", title: "ChatGPT: Your AI Starting Point", content: "ChatGPT by OpenAI is the most widely-used AI assistant. Here's how to get started:\n\n**Creating Your Account:**\n1. Go to chat.openai.com\n2. Click 'Sign up' and create a free account\n3. The free tier gives you access to GPT-3.5, which is excellent for most real estate tasks\n\n**Your First Conversation:**\nTry typing: 'I'm a real estate agent in [your city]. Help me write a compelling listing description for a 3-bedroom, 2-bathroom ranch home with a renovated kitchen and large backyard.'\n\n**Pro Tip:** Be specific! The more details you give AI, the better the output. Include square footage, neighborhood name, notable features, and your target buyer." },
      { id: "2-2", title: "Claude: The Professional's Choice", content: "Claude by Anthropic excels at longer, more nuanced content — perfect for contracts, market reports, and client presentations.\n\n**Getting Started with Claude:**\n1. Visit claude.ai\n2. Create a free account\n3. Claude's free tier is generous and ideal for business use\n\n**Why Realtors Love Claude:**\n- Handles longer documents (up to 200K tokens of context)\n- Excellent at maintaining your writing style\n- Great at analyzing data and creating reports\n- More nuanced understanding of professional communication\n\n**Try This:** Upload a past listing description you loved and ask Claude to 'analyze my writing style and create a style guide I can use for future listings.'" },
      { id: "2-3", title: "Free vs. Paid: What You Actually Need", content: "Here's the honest truth about free vs. paid AI tools:\n\n**Free Tiers Are Powerful:**\nFor most real estate tasks, free tiers of ChatGPT and Claude are more than sufficient. You can write listings, draft emails, create social posts, and analyze market data without paying a cent.\n\n**When to Upgrade ($20/month):**\n- You're using AI more than 20 times per day\n- You need the latest AI models for complex tasks\n- You want image generation capabilities\n- You need priority access during peak times\n\n**Our Recommendation:**\nStart free. Upgrade only when you hit limits. Most agents find the free tier handles 80% of their needs." },
    ],
    quiz: [
      { question: "What is the free version of ChatGPT powered by?", options: ["GPT-4", "GPT-3.5", "GPT-5", "Claude"], correct: 1 },
      { question: "What is Claude particularly good at compared to ChatGPT?", options: ["Image generation", "Voice calls", "Longer documents and nuanced content", "Social media posts only"], correct: 2 },
      { question: "When should you upgrade to a paid AI plan?", options: ["Immediately — free versions are useless", "When you're using AI more than 20 times per day", "Never — free is always sufficient", "Only if your broker requires it"], correct: 1 },
      { question: "What should you include in an AI prompt for a listing description?", options: ["Just the address", "Square footage, features, neighborhood, target buyer", "Only the price", "The MLS number"], correct: 1 },
      { question: "How much context can Claude handle in a single conversation?", options: ["1,000 words", "10,000 words", "Up to 200K tokens", "Only 500 characters"], correct: 2 },
    ]
  },
  {
    id: 3, title: "Prompt Engineering for Realtors", section: "AI Foundations", tier: "free",
    description: "Master the art of talking to AI. Learn prompt formulas that get professional results every time.",
    lessons: [
      { id: "3-1", title: "The RECIPE Prompt Formula", content: "Great AI output starts with great input. Use the RECIPE formula for consistent, professional results:\n\n**R — Role:** Tell AI who to be\n'You are an experienced luxury real estate copywriter...'\n\n**E — Example:** Show what good looks like\n'Here's an example of a listing description I love: [paste example]'\n\n**C — Context:** Provide background\n'This is a 4-bed waterfront home in the Lake Norman area, priced at $850K...'\n\n**I — Instructions:** Be specific about what you want\n'Write a 200-word listing description highlighting the water views and updated kitchen'\n\n**P — Parameters:** Set boundaries\n'Use a warm, inviting tone. Avoid clichés like \"move-in ready.\" Include a call to action.'\n\n**E — Evaluate:** Ask AI to check its work\n'Review your description for accuracy and suggest improvements.'" },
      { id: "3-2", title: "10 Ready-to-Use Prompt Templates", content: "Copy and customize these prompts for your daily work:\n\n**1. Listing Description:**\n'Write a [length]-word listing description for [property details]. Target buyer: [type]. Tone: [warm/luxury/casual]. Highlight: [top 3 features].'\n\n**2. Buyer Follow-Up Email:**\n'Draft a follow-up email to [buyer name] who viewed [property] yesterday. They loved [feature] but were concerned about [concern]. Be [tone] and suggest next steps.'\n\n**3. Market Update:**\n'Create a monthly market update for [area]. Include: median price change, inventory levels, days on market, and what this means for [buyers/sellers]. Keep it under 300 words.'\n\n**4. Social Media Post:**\n'Write an Instagram caption for [photo description]. Include relevant hashtags. Make it engaging and include a soft call to action.'\n\n**5. Neighborhood Guide:**\n'Write a 500-word neighborhood guide for [area] targeting [audience]. Include: schools, dining, recreation, commute times, and community vibe.'" },
      { id: "3-3", title: "Common Mistakes and How to Fix Them", content: "Avoid these prompt pitfalls that trip up most agents:\n\n**Mistake #1: Being Too Vague**\nBad: 'Write a listing description'\nGood: 'Write a 150-word listing description for a modern 3BR/2BA condo in downtown Austin, targeting young professionals, highlighting the rooftop pool and walkability score of 95'\n\n**Mistake #2: Not Iterating**\nAI rarely gets it perfect on the first try. Use follow-up prompts:\n- 'Make it more conversational'\n- 'Add more sensory details'\n- 'Shorten to 100 words'\n- 'Change the tone to luxury'\n\n**Mistake #3: Not Providing Your Voice**\nShare examples of YOUR writing. Say: 'Here are 3 emails I've written. Match my communication style for all future drafts.'\n\n**Mistake #4: Accepting Without Editing**\nAlways review and personalize AI output. Add local knowledge, personal touches, and verify all facts." },
    ],
    quiz: [
      { question: "What does the 'R' stand for in the RECIPE formula?", options: ["Results", "Role", "Review", "Respond"], correct: 1 },
      { question: "What is the most common prompt mistake realtors make?", options: ["Using too many details", "Being too vague", "Writing too much", "Using technical jargon"], correct: 1 },
      { question: "What should you always do after AI generates content?", options: ["Post it immediately", "Delete it and start over", "Review, edit, and personalize it", "Share it with your broker first"], correct: 2 },
      { question: "How can you get AI to match your writing style?", options: ["It's impossible", "Share examples of your past writing", "Pay for the premium version", "Use a special code word"], correct: 1 },
      { question: "What does the 'E' at the end of RECIPE stand for?", options: ["Email", "Example", "Evaluate", "Execute"], correct: 2 },
    ]
  },
  {
    id: 4, title: "AI Ethics & Compliance for Real Estate", section: "AI Foundations", tier: "free",
    description: "Navigate the legal and ethical landscape of AI in real estate, including Fair Housing compliance.",
    lessons: [
      { id: "4-1", title: "Fair Housing and AI: What You Must Know", content: "AI can inadvertently create Fair Housing violations if you're not careful. Here's what every agent must understand:\n\n**The Risk:** AI models are trained on historical data, which may contain biases. If you ask AI to describe a neighborhood's 'character' or 'ideal buyer,' it might generate language that violates Fair Housing Act protections.\n\n**Protected Classes (Federal):**\nRace, Color, National Origin, Religion, Sex, Familial Status, Disability\n\n**Safe Practices:**\n1. Never ask AI to describe the demographics of a neighborhood\n2. Review all AI-generated content for discriminatory language\n3. Focus on property features, not people features\n4. Use inclusive language in all listings and marketing\n5. Don't let AI make steering recommendations\n\n**Red Flag Phrases to Watch For:**\n- 'Perfect for young professionals' (familial status)\n- 'Walking distance to churches' (religion)\n- 'Safe neighborhood' (potential racial implication)\n- 'Master bedroom' (some MLS systems now prefer 'primary bedroom')" },
      { id: "4-2", title: "Data Privacy and Client Confidentiality", content: "When using AI tools, you're sharing information with third-party services. Here's how to protect your clients:\n\n**Never Share with AI:**\n- Social Security numbers\n- Financial documents or bank statements\n- Full legal names paired with transaction details\n- Settlement statements or closing documents\n- Medical information (even for ADA accommodations)\n\n**Safe to Share:**\n- Property features and descriptions\n- General market data\n- Generic email templates\n- Marketing copy without personal details\n\n**Best Practice:** Anonymize before you share. Instead of 'Draft an email to John Smith about his offer on 123 Main St,' try 'Draft an email to a buyer whose offer on a home was accepted, expressing excitement and outlining next steps.'" },
      { id: "4-3", title: "Disclosure: When to Tell Clients About AI", content: "Transparency builds trust. Here's when and how to disclose AI use:\n\n**When Disclosure is Recommended:**\n- When AI-generated content is presented as professional analysis\n- When AI tools access client data (with consent)\n- When clients ask about your process\n\n**How to Frame It:**\n'I use AI tools to help me work more efficiently, which means I can dedicate more time to serving you personally. All AI-generated content is reviewed and personalized by me before it reaches you.'\n\n**Your Competitive Advantage:**\nBeing transparent about AI use actually builds trust. Clients appreciate knowing you're using cutting-edge tools to serve them better, as long as the human expertise remains central.\n\n**NAR Guidelines:** The National Association of Realtors encourages AI adoption while emphasizing human oversight. Stay current with NAR's technology guidelines at nar.realtor." },
    ],
    quiz: [
      { question: "Which of these is a Fair Housing violation risk with AI?", options: ["Using AI to write listing descriptions", "Asking AI to describe a neighborhood's demographics", "Using AI for market analysis", "Drafting follow-up emails with AI"], correct: 1 },
      { question: "What should you NEVER share with an AI tool?", options: ["Property square footage", "General market trends", "Client financial documents", "Neighborhood amenities"], correct: 2 },
      { question: "What is the best practice before sharing client info with AI?", options: ["Get written consent for everything", "Anonymize the details first", "Only use paid AI tools", "Share everything — AI is confidential"], correct: 1 },
      { question: "How should you frame AI use to clients?", options: ["Don't mention it", "Say AI does all your work", "Explain it helps you work efficiently with human oversight", "Tell them AI is more accurate than humans"], correct: 2 },
      { question: "Which phrase could be a Fair Housing red flag in AI-generated content?", options: ["Spacious backyard", "Updated kitchen", "Perfect for young professionals", "Hardwood floors throughout"], correct: 2 },
    ]
  },
  {
    id: 5, title: "AI-Powered Email Mastery", section: "Essential AI Tools", tier: "free",
    description: "Transform your email game with AI. Templates for every stage of the transaction.",
    lessons: [
      { id: "5-1", title: "The 4 Email Categories Every Agent Needs", content: "Organize your AI email toolkit into four categories that cover your entire business:\n\n**1. Lead Response (Speed-to-Lead)**\nFirst contact with new leads. These need to be fast, personal, and action-oriented.\nAI Prompt: 'Write a warm, 3-sentence response to a buyer lead who inquired about [property]. Include one specific detail about the property and a question to start a conversation.'\n\n**2. Nurture Sequences**\nKeeping in touch with your database. Monthly market updates, holiday greetings, anniversary check-ins.\nAI Prompt: 'Create a 6-month email nurture sequence for past clients. One email per month, each providing genuine value about homeownership, local events, or market insights.'\n\n**3. Transaction Updates**\nKeeping clients informed during active transactions. Inspection results, appraisal updates, closing prep.\nAI Prompt: 'Draft a client update email explaining that the home inspection revealed [issue]. Be reassuring but honest. Include next steps and timeline.'\n\n**4. Referral Generation**\nAsking for referrals and reviews at the right moments.\nAI Prompt: 'Write a post-closing email thanking [client type] and naturally asking for referrals. Include a specific compliment about working with them.'" },
      { id: "5-2", title: "Building Your AI Voice Profile", content: "The biggest complaint about AI emails? They sound generic. Fix this by creating a Voice Profile:\n\n**Step 1: Gather Your Best Emails**\nFind 5-10 emails you've written that got great responses. These represent your natural voice.\n\n**Step 2: Create Your Profile Prompt**\n'Analyze these email examples and create a writing style guide for me. Note my:\n- Typical greeting and sign-off\n- Sentence length and complexity\n- Use of humor or formality\n- How I structure information\n- Words and phrases I commonly use\n- My overall tone'\n\n**Step 3: Use It Every Time**\nStart each email request with: 'Using my voice profile [paste profile], write an email that...'\n\n**Step 4: Refine Over Time**\nEvery month, update your voice profile with new examples of emails that worked well.\n\n**Pro Tip:** Save your voice profile as a document. Copy and paste it at the start of every email prompt." },
      { id: "5-3", title: "Speed-to-Lead: The 2-Minute Response System", content: "Studies show that responding to leads within 5 minutes increases conversion by 400%. Here's your AI-powered system:\n\n**Pre-Build 10 Response Templates:**\nCreate AI-generated templates for your most common lead types:\n1. Zillow/Realtor.com property inquiry\n2. Open house sign-in follow-up\n3. Website contact form\n4. Social media DM\n5. Referral introduction\n6. Expired listing outreach\n7. FSBO outreach\n8. Relocation inquiry\n9. Investment property inquiry\n10. First-time buyer inquiry\n\n**The 2-Minute Workflow:**\n1. Lead comes in (30 seconds to read)\n2. Select the matching template (10 seconds)\n3. Customize 2-3 details: name, property, personal touch (60 seconds)\n4. Review and send (20 seconds)\n\n**The Personal Touch That Matters:**\nAlways add ONE specific detail that shows you're a real person:\n- Reference something from their inquiry\n- Mention a specific neighborhood detail\n- Note the current weather or local event" },
    ],
    quiz: [
      { question: "What are the 4 email categories every agent needs?", options: ["Morning, afternoon, evening, weekend", "Lead response, nurture, transaction, referral", "Buyers, sellers, investors, renters", "Short, medium, long, follow-up"], correct: 1 },
      { question: "How much does responding within 5 minutes increase lead conversion?", options: ["50%", "100%", "200%", "400%"], correct: 3 },
      { question: "What is an AI Voice Profile?", options: ["A recording of your voice", "A style guide based on your best writing", "Your AI account settings", "A headshot for your email signature"], correct: 1 },
      { question: "What should you always add to an AI-generated email?", options: ["More buzzwords", "A longer signature", "One specific personal detail", "Multiple property links"], correct: 2 },
      { question: "How often should you update your Voice Profile?", options: ["Never — set it once", "Monthly", "Every year", "Only when AI updates"], correct: 1 },
    ]
  },
  {
    id: 6, title: "AI for Market Analysis", section: "Essential AI Tools", tier: "free",
    description: "Use AI to analyze market trends, create CMAs, and build client-ready market reports.",
    lessons: [
      { id: "6-1", title: "Creating AI-Enhanced CMAs", content: "A Comparative Market Analysis is one of your most important tools. AI can make yours stand out:\n\n**The AI-Enhanced CMA Process:**\n1. Pull your comparable sales data from MLS (you still need the data)\n2. Feed the data to AI with this prompt:\n\n'Analyze these comparable sales for [subject property address]:\n[Paste comp data: address, sale price, sqft, beds/baths, sale date, condition]\n\nCreate a market analysis narrative that explains:\n- Why these comps were selected\n- How each comp compares to the subject property\n- Adjustments for differences (size, condition, features, timing)\n- A recommended list price range with justification\n- Current market conditions affecting pricing\n\nWrite it for a homeowner audience — professional but not technical.'\n\n**What AI Does Best:** Turning raw numbers into a compelling story that helps clients understand their home's value.\n\n**What You Still Need to Do:** Verify the data, apply your local market knowledge, and make the final pricing recommendation." },
      { id: "6-2", title: "Monthly Market Reports That Clients Love", content: "Stand out in your market by sending AI-powered monthly reports:\n\n**The 5-Section Monthly Report:**\n\n**1. Market Snapshot** (3-4 sentences)\nMedian price, inventory, days on market vs. last month\n\n**2. What This Means for Buyers** (2-3 sentences)\nPractical advice based on current conditions\n\n**3. What This Means for Sellers** (2-3 sentences)\nPractical advice for the other side\n\n**4. Featured Neighborhood Spotlight** (4-5 sentences)\nRotate through neighborhoods each month\n\n**5. My Take** (2-3 sentences)\nYour personal prediction or observation — this is where YOUR expertise shines\n\n**AI Prompt Template:**\n'Using this market data for [area] in [month/year]:\n[Paste stats]\n\nWrite a monthly market report following this 5-section format. Keep the total under 400 words. Tone: knowledgeable but approachable. End with a subtle call to action.'" },
      { id: "6-3", title: "Investment Analysis with AI", content: "Help investor clients make data-driven decisions using AI:\n\n**Rental Property Analysis Prompt:**\n'Analyze this potential rental investment:\n- Purchase price: $___\n- Estimated monthly rent: $___\n- Property taxes: $___/year\n- Insurance: $___/year\n- HOA (if any): $___/month\n- Estimated maintenance: ___% of rent\n- Down payment: ___%\n- Interest rate: ___%\n\nCalculate and explain:\n1. Monthly cash flow (positive or negative)\n2. Cap rate\n3. Cash-on-cash return\n4. Break-even occupancy rate\n5. 5-year projected ROI\n\nPresent this in a format suitable for an investor client.'\n\n**Why This Works:** You provide the local market knowledge (realistic rent estimates, maintenance costs), and AI does the math and creates a professional presentation. This positions you as the go-to agent for investors in your market." },
    ],
    quiz: [
      { question: "What does AI do best in a CMA?", options: ["Pulls MLS data automatically", "Turns raw numbers into compelling narratives", "Sets the final list price", "Generates comparable sales"], correct: 1 },
      { question: "How many sections should a monthly market report have?", options: ["3", "5", "7", "10"], correct: 1 },
      { question: "What should the 'My Take' section of a market report include?", options: ["Just the statistics", "Your personal prediction or observation", "A disclaimer", "Links to listings"], correct: 1 },
      { question: "What does 'cap rate' measure in investment analysis?", options: ["Monthly mortgage payment", "Annual return on property value", "Tax deductions", "Appreciation rate"], correct: 1 },
      { question: "What is YOUR role when AI generates a CMA narrative?", options: ["Nothing — AI handles it all", "Verify data, apply local knowledge, make final recommendation", "Just add your logo", "Forward it to the client unchanged"], correct: 1 },
    ]
  },
  {
    id: 7, title: "AI-Powered Social Media", section: "Essential AI Tools", tier: "free",
    description: "Build a consistent social media presence with AI-generated content calendars and posts.",
    lessons: [
      { id: "7-1", title: "The 30-Day Content Calendar", content: "Stop scrambling for social media ideas. Let AI build your monthly calendar:\n\n**Content Pillar Strategy:**\nOrganize posts into 5 pillars that rotate throughout the week:\n- Monday: Market Monday (stats, trends, insights)\n- Tuesday: Tip Tuesday (buyer/seller advice)\n- Wednesday: Listing Spotlight\n- Thursday: Neighborhood Feature\n- Friday: Fun Friday (personal, behind-the-scenes)\n\n**AI Prompt for Calendar:**\n'Create a 30-day social media content calendar for a real estate agent in [city]. Follow this pillar schedule: [pillars]. For each day, provide:\n1. Post topic\n2. Caption (150 words max)\n3. Image description/suggestion\n4. 5 relevant hashtags\n5. Best time to post\n\nVoice: [your brand voice]. Mix educational, entertaining, and promotional content (60/30/10 ratio).'\n\n**Pro Tip:** Generate the full month in one sitting, then schedule using a tool like Later or Buffer." },
      { id: "7-2", title: "Platform-Specific Strategies", content: "Each platform has different rules. Here's how to adapt with AI:\n\n**Instagram (Visual-First):**\nAI Prompt: 'Write an Instagram carousel post about [topic]. Create 5-7 slides with a hook on slide 1, valuable content on slides 2-6, and a CTA on the last slide. Keep text short — 20 words max per slide.'\n\n**LinkedIn (Professional):**\nAI Prompt: 'Write a LinkedIn post about [real estate insight]. Start with a bold opening line. Use short paragraphs. Include a personal anecdote. End with a question to encourage comments. 200 words max.'\n\n**Facebook (Community):**\nAI Prompt: 'Write a Facebook post for a real estate agent about [topic]. Make it conversational and community-focused. Include a question to encourage engagement. 100-150 words.'\n\n**TikTok/Reels (Short Video Scripts):**\nAI Prompt: 'Write a 30-second video script about [real estate tip]. Hook in first 3 seconds. Deliver one clear takeaway. End with a call to action. Include visual direction notes.'" },
      { id: "7-3", title: "Hashtag Strategy and Engagement", content: "AI can optimize your hashtag game and help you engage meaningfully:\n\n**The 3-Tier Hashtag Formula:**\n1. **Broad** (500K+ posts): #realestate #homebuying #dreamhome\n2. **Niche** (10K-500K): #[city]realtor #firsttimebuyertips #luxuryliving\n3. **Hyper-Local** (under 10K): #[neighborhood]homes #[city]realestate\n\n**AI Prompt for Hashtags:**\n'Generate 30 hashtags for a real estate agent in [city] organized into three tiers: broad (10), niche (10), and hyper-local (10). I specialize in [specialty].'\n\n**AI for Engagement Responses:**\nWhen someone comments on your posts, use AI to help craft thoughtful responses:\n'Someone commented [comment] on my post about [topic]. Write a warm, genuine response that continues the conversation and positions me as helpful. 2-3 sentences max.'\n\n**Key Rule:** Never automate engagement responses. Use AI as a starting point, then personalize." },
    ],
    quiz: [
      { question: "What is the recommended content ratio for social media?", options: ["100% promotional", "50/50 educational and promotional", "60% educational, 30% entertaining, 10% promotional", "All listing posts"], correct: 2 },
      { question: "What should always be on the first slide of an Instagram carousel?", options: ["Your headshot", "A hook that grabs attention", "Your contact info", "The hashtags"], correct: 1 },
      { question: "How many tiers should your hashtag strategy have?", options: ["1", "2", "3", "5"], correct: 2 },
      { question: "Should you automate AI engagement responses?", options: ["Yes — saves time", "No — use AI as starting point, then personalize", "Only on weekends", "Only for negative comments"], correct: 1 },
      { question: "What content pillar is recommended for Mondays?", options: ["Fun content", "Listing spotlight", "Market data and insights", "Neighborhood features"], correct: 2 },
    ]
  },
  {
    id: 8, title: "AI Writing Workshop", section: "Essential AI Tools", tier: "free",
    description: "Hands-on practice writing listings, bios, and marketing copy with AI assistance.",
    lessons: [
      { id: "8-1", title: "Writing Compelling Listing Descriptions", content: "The 5-component formula for AI-assisted listing descriptions:\n\n**Component 1: The Hook (First Sentence)**\nGrab attention immediately. Never start with the address.\nBad: '123 Main Street is a 3-bedroom home.'\nGood: 'Sun-drenched mornings and chef-worthy dinners await in this beautifully renovated Craftsman.'\n\n**Component 2: The Story (2-3 Sentences)**\nPaint a picture of the lifestyle, not just the features.\n'Imagine weekend brunches on the wraparound porch, kids playing in the fenced backyard, and cozy evenings by the stone fireplace.'\n\n**Component 3: The Features (3-5 Highlights)**\nLead with what makes this property special.\n\n**Component 4: The Neighborhood (1-2 Sentences)**\nLocate the home in its community context.\n\n**Component 5: The Close (Call to Action)**\nCreate urgency without being pushy.\n'Schedule your private tour before this gem finds its forever family.'\n\n**AI Prompt:**\n'Using the 5-component listing formula (hook, story, features, neighborhood, close), write a [word count]-word listing description for: [all property details]. Target buyer: [description]. Tone: [warm/luxury/energetic].'" },
      { id: "8-2", title: "Crafting Your Agent Bio", content: "Your bio is often the first thing potential clients read. Here's how to make it convert:\n\n**The 4-Part Bio Framework:**\n\n**1. Opening Hook:**\nLead with what makes you different, not your license date.\n'Sherry Perry doesn't just sell homes — she helps families find where their next chapter begins.'\n\n**2. Your Story:**\nWhy real estate? What drives you? Make it human.\n\n**3. Your Results:**\nSpecific numbers and achievements. Quantify your success.\n\n**4. Personal Touch:**\nOne or two personal details that make you relatable.\n\n**AI Prompt:**\n'Write a real estate agent bio for [name] using this framework:\n- Hook: What makes me unique is [differentiator]\n- Story: I got into real estate because [reason]\n- Results: [years experience], [homes sold], [areas served], [specialties]\n- Personal: Outside of real estate, I [hobbies/family]\n\nWrite in first person. 200 words. Tone: [warm and professional/energetic/luxury].'" },
      { id: "8-3", title: "Marketing Copy That Converts", content: "From email subject lines to ad copy, AI can help you write marketing that gets results:\n\n**Email Subject Lines (Test 3-5 per campaign):**\nAI Prompt: 'Generate 10 email subject lines for [campaign type]. Each should be under 50 characters. Mix curiosity, urgency, and value. Target: [audience].'\n\n**Open House Invitations:**\nAI Prompt: 'Write an open house invitation for [property] this [day/time]. Make it feel exclusive, not generic. Include one unique detail about the property. Add RSVP instructions. 100 words.'\n\n**Just Sold/Just Listed Postcards:**\nAI Prompt: 'Write front-and-back copy for a [just sold/just listed] postcard. Front: attention-grabbing headline + 1 sentence. Back: property highlights, market insight, and call to action. Keep it scannable.'\n\n**Google/Facebook Ad Copy:**\nAI Prompt: 'Write 3 variations of a [Google/Facebook] ad for [objective]. Include headline (30 chars), description (90 chars), and call to action. Target: [audience in city].'" },
    ],
    quiz: [
      { question: "What is the first component of the listing description formula?", options: ["The address", "The price", "A hook/attention-grabber", "The square footage"], correct: 2 },
      { question: "What should your agent bio lead with?", options: ["Your license date", "What makes you different", "Your brokerage name", "Your phone number"], correct: 1 },
      { question: "How many email subject line variations should you test per campaign?", options: ["1", "3-5", "10-15", "Just use one every time"], correct: 1 },
      { question: "What should a listing description NEVER start with?", options: ["A lifestyle statement", "The address", "A question", "An emotional hook"], correct: 1 },
      { question: "What tone options work best for luxury property descriptions?", options: ["Casual and fun", "Elegant and aspirational", "Urgent and aggressive", "Technical and detailed"], correct: 1 },
    ]
  },
  // Premium Tier Modules (9-17)
  {
    id: 9, title: "AI Listing Description Mastery", section: "Real Estate AI Workflows", tier: "premium",
    description: "Advanced listing techniques including multi-platform optimization and photo-based descriptions.",
    lessons: [
      { id: "9-1", title: "Multi-Platform Listing Optimization", content: "Different platforms have different character limits and audiences. Optimize your listings for each:\n\n**MLS (Full Description):** 500-1000 words, feature-rich, SEO keywords\n**Zillow/Realtor.com:** 250-400 words, buyer-emotional, lifestyle-focused\n**Social Media:** 150 words max, hook-first, hashtag-optimized\n**Print/Flyer:** 75-100 words, scannable, bullet-friendly\n\nAI Prompt: 'I have this full listing description: [paste]. Now create optimized versions for: 1) Zillow (300 words), 2) Instagram (150 words with hashtags), 3) Print flyer (75 words with bullet points). Maintain the same voice and key selling points across all versions.'" },
      { id: "9-2", title: "Photo-Based Description Generation", content: "Leverage AI vision capabilities to generate descriptions from listing photos:\n\n**The Process:**\n1. Upload your best 5-10 listing photos to Claude or ChatGPT (paid versions support images)\n2. Use this prompt: 'Based on these listing photos, write a compelling description. Identify: architectural style, notable features visible, condition/updates, natural light quality, outdoor spaces, and overall vibe. 300 words, warm and inviting tone.'\n\n**Why This Works:** AI can spot details you might overlook and describe them in fresh, creative language.\n\n**Best Practice:** Always verify AI's observations against reality. AI might misidentify materials or features." },
      { id: "9-3", title: "The 5-Component Listing Formula Deep Dive", content: "Take your listing descriptions from good to exceptional:\n\n**Advanced Hook Techniques:**\n- Question hooks: 'What if your morning commute was a walk through tree-lined streets?'\n- Statistic hooks: 'In a market where homes sell in 7 days, this one deserves a second look.'\n- Sensory hooks: 'The scent of fresh herbs from the kitchen garden greets you at the door.'\n\n**Storytelling Mastery:**\nDon't describe rooms — describe moments. Not 'large kitchen with granite counters' but 'Sunday morning pancakes on the granite island while the kids set the breakfast nook table.'\n\n**AI Prompt for Premium Listings:**\n'Write a luxury listing description using sensory language and lifestyle storytelling. Property: [details]. Budget buyer: [profile]. I want the reader to FEEL what living here is like. 400 words. Include one unexpected detail that creates memorability.'" },
    ],
    quiz: [
      { question: "What is the ideal length for a Zillow listing description?", options: ["75 words", "150 words", "250-400 words", "1000+ words"], correct: 2 },
      { question: "What should you always do after AI generates a photo-based description?", options: ["Post it immediately", "Verify observations against reality", "Add more photos", "Delete the photos"], correct: 1 },
      { question: "What type of hook uses sensory details?", options: ["Question hook", "Statistic hook", "Sensory hook", "Price hook"], correct: 2 },
      { question: "Instead of describing rooms, what should you describe?", options: ["Square footage", "Paint colors", "Moments and lifestyle", "Construction materials"], correct: 2 },
      { question: "For social media listings, what's the maximum recommended word count?", options: ["50 words", "150 words", "400 words", "1000 words"], correct: 1 },
    ]
  },
  {
    id: 10, title: "Client Communication Mastery", section: "Real Estate AI Workflows", tier: "premium",
    description: "Build AI-powered communication systems for every client touchpoint.",
    lessons: [
      { id: "10-1", title: "Lead Response Sequences", content: "Build automated yet personal-feeling response sequences:\n\n**The 7-Touch Lead Sequence:**\nDay 1: Immediate response (within 2 minutes) — personal, specific to inquiry\nDay 2: Value-add follow-up — share relevant market insight\nDay 4: Social proof — mention recent client success story\nDay 7: Resource share — send neighborhood guide or market report\nDay 14: Check-in — casual, non-pushy reconnection\nDay 21: Value offer — free CMA, buyer consultation, etc.\nDay 30: Long-term nurture transition — add to monthly newsletter\n\nAI Prompt: 'Create a 7-touch email sequence for a [buyer/seller] lead in [area]. Each email should feel personal and provide genuine value. Include subject lines. The sequence should gradually build trust without being pushy.'" },
      { id: "10-2", title: "Transaction Update Templates", content: "Keep clients informed and calm throughout the transaction:\n\n**Key Milestone Updates:**\n1. Offer accepted congratulations\n2. Inspection scheduled notification\n3. Inspection results explanation\n4. Appraisal update\n5. Loan approval celebration\n6. Closing prep checklist\n7. Post-closing thank you + next steps\n\nAI Prompt: 'Write a client email explaining that the home inspection found [specific issues]. Strike a balance between honest transparency and reassurance. Explain what these findings typically mean, what our options are, and recommend next steps. Keep the tone calm and confident.'" },
      { id: "10-3", title: "Building Your Voice Profile System", content: "Advanced voice matching for truly personalized AI communications:\n\n**The Voice Profile Document:**\nCreate a master document with:\n- 10 examples of your best emails\n- Your preferred greetings and sign-offs\n- Words you love and words you never use\n- Your humor style (or lack thereof)\n- Your communication philosophy\n\n**Using It Consistently:**\nStart EVERY AI prompt with: 'Using my voice profile below, [instruction]. Voice Profile: [paste]'\n\n**Seasonal Updates:**\nUpdate your voice profile quarterly with fresh examples. Your communication style evolves, and your AI should evolve with it." },
    ],
    quiz: [
      { question: "How many touches are in the recommended lead sequence?", options: ["3", "5", "7", "10"], correct: 2 },
      { question: "When should the first lead response go out?", options: ["Within 24 hours", "Within 2 minutes", "Within 1 week", "When you have time"], correct: 1 },
      { question: "How often should you update your Voice Profile?", options: ["Never", "Monthly", "Quarterly", "Annually"], correct: 2 },
      { question: "What tone should an inspection results email strike?", options: ["Alarming and urgent", "Honest transparency with reassurance", "Overly optimistic", "Legal and technical"], correct: 1 },
      { question: "What is the purpose of Touch #4 in the lead sequence?", options: ["Close the deal", "Share a resource like a neighborhood guide", "Ask for referrals", "Send a contract"], correct: 1 },
    ]
  },
  {
    id: 11, title: "CMA & Market Analysis Pro", section: "Real Estate AI Workflows", tier: "premium",
    description: "Advanced market analysis techniques including investor reports and buyer briefs.",
    lessons: [
      { id: "11-1", title: "Narrative CMA Reports", content: "Transform your CMAs from spreadsheets into compelling stories:\n\n**The Narrative Approach:**\nInstead of just showing numbers, tell the story of the market.\n\n'The [neighborhood] market has shifted notably in the past 90 days. While the median price increased 4.2% to $485,000, the real story is in the details: homes with updated kitchens are selling 12 days faster and commanding 8% premiums over comparable properties without updates.\n\nFor your home at [address], this means...'\n\n**AI Prompt:**\n'Create a narrative CMA report for [address]. Data: [comp details]. Write it as a story, not a spreadsheet. Explain WHY prices are what they are, not just what they are. Include adjustment explanations a homeowner would understand. 500 words, professional but conversational.'" },
      { id: "11-2", title: "Buyer Market Briefs", content: "Give your buyer clients a competitive edge with AI-generated market briefs:\n\n**The Buyer Brief Template:**\n1. Current market conditions in their target area\n2. Price trend analysis (is it getting more or less competitive?)\n3. Inventory analysis (how many options are available?)\n4. Strategy recommendations based on conditions\n5. Comparable recent sales to set expectations\n\nAI Prompt: 'Create a buyer market brief for someone looking in [area] with a budget of $[amount] for a [property type]. Include: current conditions, price trends, available inventory analysis, and strategic recommendations for making competitive offers in this market.'" },
      { id: "11-3", title: "Investment Analysis Reports", content: "Position yourself as the go-to agent for investors with detailed AI-generated analysis:\n\n**The Complete Investment Report:**\n1. Property overview and acquisition cost analysis\n2. Rental income projections (conservative, moderate, aggressive)\n3. Operating expense breakdown\n4. Cash flow analysis (monthly and annual)\n5. ROI metrics: cap rate, cash-on-cash return, GRM\n6. 5-year appreciation projection\n7. Risk factors and mitigation strategies\n\nAI Prompt: 'Create a comprehensive investment analysis for [property]. Purchase price: $[X]. Estimated rent: $[X]/month. Include three scenarios (conservative, moderate, aggressive) for rental income. Calculate all standard investment metrics. Present risks honestly. Format for a sophisticated investor audience.'" },
    ],
    quiz: [
      { question: "What makes a narrative CMA different from a traditional one?", options: ["It uses bigger fonts", "It tells the story behind the numbers", "It excludes comparable sales", "It's always shorter"], correct: 1 },
      { question: "How many sections should a buyer market brief have?", options: ["2", "3", "5", "10"], correct: 2 },
      { question: "What investment metric measures annual return relative to property value?", options: ["Cash-on-cash return", "Cap rate", "GRM", "ROI"], correct: 1 },
      { question: "How many rental income scenarios should an investment report include?", options: ["1 (best case)", "2 (best and worst)", "3 (conservative, moderate, aggressive)", "5 scenarios"], correct: 2 },
      { question: "What should a CMA narrative explain that numbers alone cannot?", options: ["The MLS number", "WHY prices are what they are", "The agent's commission", "The loan terms"], correct: 1 },
    ]
  },
  {
    id: 12, title: "AI Marketing Systems", section: "Real Estate AI Workflows", tier: "premium",
    description: "Build complete marketing campaigns with AI — from email sequences to print materials.",
    lessons: [
      { id: "12-1", title: "Social Media Content Calendars", content: "Build a 90-day content engine using AI:\n\n**The Content Pillar System:**\nCreate 5 content categories and rotate them:\n1. Market Insights (educational)\n2. Property Features (promotional)\n3. Community Spotlight (engagement)\n4. Behind the Scenes (personal)\n5. Client Success Stories (social proof)\n\n**AI Prompt for 90 Days:**\n'Create a 90-day social media calendar for a real estate agent in [city]. 5 posts per week using these pillars: [list]. For each post: topic, platform (Instagram/LinkedIn/Facebook), caption (platform-optimized length), image suggestion, and 5 hashtags. Include seasonal/holiday tie-ins.'" },
      { id: "12-2", title: "Email Campaign Architecture", content: "Build email campaigns that nurture leads into clients:\n\n**Campaign Types:**\n1. Welcome Series (new subscribers): 5 emails over 2 weeks\n2. Buyer Education: 8 emails over 4 weeks\n3. Seller Preparation: 6 emails over 3 weeks\n4. Past Client Nurture: Monthly for 12 months\n5. Market Update: Monthly newsletter\n\nAI Prompt: 'Create a [campaign type] email sequence. Number of emails: [X]. Spacing: [frequency]. Each email needs: subject line (under 50 chars), preview text (under 100 chars), body copy (under 300 words), and CTA. The series should progressively build trust and lead toward [goal].'" },
      { id: "12-3", title: "Print and Digital Materials", content: "Use AI to create compelling copy for all your marketing materials:\n\n**Just Listed/Just Sold Postcards:**\n'Write postcard copy for a [just listed/just sold] announcement. Property: [details]. Front: bold headline + one sentence hook. Back: 3 key features, market context sentence, and CTA with contact info. Make it scannable — use short phrases.'\n\n**Neighborhood Guides:**\n'Create a comprehensive neighborhood guide for [area]. Include: overview, schools, dining, recreation, commute info, market snapshot, and why people love living here. 800 words. Include section headers. Target: [audience].'\n\n**Property Brochures:**\n'Write copy for a luxury property brochure for [address]. Pages: cover (headline + tagline), lifestyle page (300 words), features page (organized by category), floor plan page (room descriptions), neighborhood page, agent bio page. Tone: sophisticated and aspirational.'" },
    ],
    quiz: [
      { question: "How many content pillars should your social media strategy have?", options: ["2", "3", "5", "10"], correct: 2 },
      { question: "What's the recommended length for a welcome email series?", options: ["1 email", "5 emails over 2 weeks", "20 emails over 6 months", "Just one newsletter"], correct: 1 },
      { question: "What should the front of a postcard include?", options: ["Your full bio", "Bold headline + one sentence hook", "Market statistics", "Multiple property photos"], correct: 1 },
      { question: "What is the 60/30/10 content ratio?", options: ["60% video, 30% photos, 10% text", "60% educational, 30% entertaining, 10% promotional", "60% listings, 30% sold, 10% personal", "60% Instagram, 30% Facebook, 10% LinkedIn"], correct: 1 },
      { question: "How long should a neighborhood guide be?", options: ["100 words", "300 words", "800 words", "2000 words"], correct: 2 },
    ]
  },
  {
    id: 13, title: "Transaction Management with AI", section: "Advanced AI Strategies", tier: "premium",
    description: "Streamline your transactions with AI-powered timelines, checklists, and workflows.",
    lessons: [
      { id: "13-1", title: "AI Transaction Timelines", content: "Never miss a deadline with AI-generated transaction management:\n\n**The Smart Timeline System:**\nAI Prompt: 'Create a detailed transaction timeline for a [purchase/sale] in [state]. Closing date: [date]. Include every key milestone with:\n- Action item\n- Responsible party (buyer, seller, agent, lender, title)\n- Deadline\n- What happens if missed\n- Reminder timing (when to follow up)\n\nState-specific requirements for [state]. Format as a checklist.'\n\n**Pro Tip:** Generate a new timeline for each transaction, customized to the specific deal terms, financing type, and state requirements." },
      { id: "13-2", title: "Document Preparation Workflows", content: "Use AI to prepare and review transaction documents efficiently:\n\n**Pre-Listing Checklist:**\nAI Prompt: 'Create a comprehensive pre-listing document checklist for a [property type] in [state]. Include every document the seller needs to gather, every disclosure required, and every form I need to prepare. Organize by category: seller documents, property documents, required disclosures, listing agreement components.'\n\n**Post-Inspection Action Plans:**\nAI Prompt: 'The home inspection revealed these issues: [list]. Create an action plan that: 1) Categorizes each issue (safety, structural, cosmetic, maintenance), 2) Estimates repair costs, 3) Recommends which to request repair vs. credit, 4) Drafts repair request language for the amendment.'" },
      { id: "13-3", title: "Post-Closing Workflows", content: "The transaction ends at closing, but the relationship doesn't:\n\n**30-Day Post-Closing Sequence:**\nDay 1: Closing day congratulations + gift delivery\nDay 3: 'How's the move going?' check-in\nDay 7: Utility setup reminder + local vendor recommendations\nDay 14: 'Settling in?' check-in + neighborhood guide\nDay 30: Homeownership tips + request for review\n\n**Annual Client Care Calendar:**\nAI Prompt: 'Create a 12-month post-closing client care calendar. Include: seasonal home maintenance reminders, home anniversary acknowledgment, market value update, property tax reminder, and 4 touchpoints that provide genuine value. Make each contact feel personal, not automated.'" },
    ],
    quiz: [
      { question: "What should an AI transaction timeline include for each milestone?", options: ["Just the date", "Action, responsible party, deadline, consequences, reminder timing", "Only the agent's tasks", "Just the closing date"], correct: 1 },
      { question: "How should inspection issues be categorized?", options: ["By room", "Safety, structural, cosmetic, maintenance", "By cost only", "By who caused them"], correct: 1 },
      { question: "When should the post-closing review request be sent?", options: ["Closing day", "Day 3", "Day 14", "Day 30"], correct: 3 },
      { question: "Why generate a new timeline for each transaction?", options: ["AI forgets previous ones", "Each deal has unique terms, financing, and state requirements", "It's required by law", "Clients expect it"], correct: 1 },
      { question: "What should the annual client care calendar include?", options: ["Monthly sales pitches", "Seasonal maintenance, anniversary, value updates, genuine value", "Only holiday cards", "Quarterly CMA reports"], correct: 1 },
    ]
  },
  {
    id: 14, title: "Social Media Strategy Pro", section: "Advanced AI Strategies", tier: "premium",
    description: "Advanced social strategies including brand voice development and content repurposing.",
    lessons: [
      { id: "14-1", title: "Brand Voice Development", content: "Create a consistent, recognizable brand voice across all platforms:\n\n**The Brand Voice Workshop:**\n1. Define your brand personality (3-5 adjectives)\n2. Identify your unique perspective on real estate\n3. Create your 'do' and 'don't' language guide\n4. Establish your visual style consistency\n\nAI Prompt: 'I'm a real estate agent who wants to be known for [qualities]. My target audience is [description]. My unique angle is [differentiator]. Create a comprehensive brand voice guide that includes: tone descriptors, vocabulary preferences (words to use/avoid), content themes, and example posts showing the voice in action across Instagram, LinkedIn, and Facebook.'" },
      { id: "14-2", title: "Content Repurposing Engine", content: "Create once, publish everywhere — the smart way:\n\n**The 1-to-7 Method:**\nStart with one piece of long-form content and transform it into 7 pieces:\n1. Long blog post or article (original)\n2. Instagram carousel (key points)\n3. LinkedIn article (professional angle)\n4. Facebook post (community angle)\n5. Email newsletter feature\n6. Video script (1-2 minutes)\n7. Twitter/X thread\n\nAI Prompt: 'Take this article I wrote: [paste]. Now repurpose it into 6 additional formats: Instagram carousel (5 slides), LinkedIn post (200 words), Facebook post (150 words), email excerpt (100 words with link), 60-second video script, and Twitter thread (5 tweets). Maintain the core message but adapt for each platform's audience and format.'" },
      { id: "14-3", title: "Engagement and Growth Strategies", content: "Use AI to analyze and improve your social media performance:\n\n**Weekly Review Prompt:**\n'Here are my top 5 performing posts this week: [paste]. And my 3 worst: [paste]. Analyze: What made the top posts work? What can I learn from the underperformers? Give me 5 specific recommendations for next week's content based on these patterns.'\n\n**Community Building:**\nAI Prompt: 'I want to build a local real estate community on [platform]. Create a strategy that includes: group/community name suggestions, weekly content themes, engagement prompts, rules/guidelines, and a 30-day launch plan to get the first 100 members.'\n\n**Collaboration Strategy:**\n'Create a list of 10 types of local businesses I should collaborate with for cross-promotion. For each, suggest a specific collaboration idea and a DM template I can send to initiate the partnership.'" },
    ],
    quiz: [
      { question: "How many adjectives should define your brand personality?", options: ["1", "3-5", "10-15", "As many as possible"], correct: 1 },
      { question: "What is the '1-to-7 Method'?", options: ["Post 7 times a day", "Transform 1 piece of content into 7 formats", "Follow 7 influencers", "Use 7 hashtags per post"], correct: 1 },
      { question: "How often should you review social media performance?", options: ["Monthly", "Weekly", "Daily", "Quarterly"], correct: 1 },
      { question: "What's a good first goal for a community group?", options: ["1,000 members in a week", "100 members in 30 days", "10,000 followers", "Go viral immediately"], correct: 1 },
      { question: "What makes a brand voice consistent?", options: ["Using the same photo everywhere", "Defined personality, vocabulary, and tone guide", "Posting at the same time", "Same hashtags every post"], correct: 1 },
    ]
  },
  {
    id: 15, title: "Presentations & Client Materials", section: "Advanced AI Strategies", tier: "premium",
    description: "Create stunning listing presentations, buyer guides, and pitch materials with AI.",
    lessons: [
      { id: "15-1", title: "The Winning Listing Presentation", content: "Build a listing presentation framework that wins:\n\n**The 10-Slide Structure:**\n1. Cover: Your brand + property address\n2. About You: Credibility and track record\n3. Market Analysis: Current conditions\n4. Pricing Strategy: CMA summary\n5. Marketing Plan: Your full strategy\n6. Online Presence: Digital marketing approach\n7. Photography & Staging: Visual strategy\n8. Timeline: From listing to closing\n9. Communication: How you keep them informed\n10. Next Steps: Clear path forward\n\nAI Prompt: 'Create the content for a 10-slide listing presentation for [property]. My track record: [stats]. The seller's main concerns are [concerns]. Write compelling content for each slide that addresses their concerns while showcasing my value.'" },
      { id: "15-2", title: "Buyer Guides That Convert", content: "Create comprehensive buyer guides that establish your expertise:\n\nAI Prompt: 'Create a first-time buyer guide for the [city] market. Include: step-by-step buying process, current market conditions, financing options, what to expect at each stage, common mistakes to avoid, and local-specific tips. 2000 words, organized with clear headers. Tone: encouraging and informative.'\n\n**Sections to Include:**\n1. The Home Buying Journey (overview timeline)\n2. Financial Preparation (credit, savings, pre-approval)\n3. Working with an Agent (your value proposition)\n4. The Search Process\n5. Making an Offer\n6. Under Contract to Closing\n7. Moving Day and Beyond" },
      { id: "15-3", title: "Quick-Turn Materials", content: "Generate professional materials on tight deadlines:\n\n**Open House Flyers (5 minutes):**\n'Create open house flyer copy for [property] on [date/time]. Include: headline, 3 key features, agent info, and a QR code call-to-action suggestion. Fit on one page.'\n\n**Client Thank You Notes (2 minutes):**\n'Write a heartfelt closing day note for [client names] who just [bought/sold] [property type] in [area]. Reference [specific detail from our work together]. Handwritten style, 4-5 sentences.'\n\n**Market Snapshot Graphics (3 minutes):**\n'Create text content for a market snapshot infographic. Area: [area]. Stats: [data]. Format: 5 key stats with brief explanations. Make each stat have a headline, number, and one-sentence context.'" },
    ],
    quiz: [
      { question: "How many slides should a winning listing presentation have?", options: ["5", "10", "20", "30"], correct: 1 },
      { question: "What should Slide 4 of a listing presentation cover?", options: ["Your bio", "Market analysis", "Pricing strategy with CMA", "Photography plan"], correct: 2 },
      { question: "How long should a quick-turn open house flyer take to create with AI?", options: ["5 minutes", "30 minutes", "2 hours", "1 day"], correct: 0 },
      { question: "What should a first-time buyer guide's tone be?", options: ["Technical and legal", "Encouraging and informative", "Urgent and aggressive", "Minimal and brief"], correct: 1 },
      { question: "What makes a closing thank-you note personal?", options: ["Using fancy stationery", "Referencing a specific detail from working together", "Making it long", "Including market stats"], correct: 1 },
    ]
  },
  {
    id: 16, title: "AI Business Systems", section: "Advanced AI Strategies", tier: "premium",
    description: "Build AI systems that run your business: morning briefings, listing launches, and ROI tracking.",
    lessons: [
      { id: "16-1", title: "The AI Morning Briefing", content: "Start every day informed and ready with your AI-powered morning routine:\n\n**The 5-Minute Morning Briefing:**\n1. Check MLS for new listings matching buyer criteria\n2. Review overnight leads and prioritize\n3. Check today's transaction deadlines\n4. Generate daily social media post\n5. Review market news headlines\n\nAI Prompt: 'Create my morning briefing. Today's date: [date]. Active buyers looking for: [criteria]. Active listings: [addresses]. Pending transactions: [details]. Generate: 1) Buyer match alerts, 2) Priority task list, 3) Today's social media post about [topic], 4) Any deadlines within 48 hours.'" },
      { id: "16-2", title: "The Listing Launch System", content: "Systematize your listing launches for maximum impact:\n\n**7-Day Listing Launch Sequence:**\nDay -3: Coming Soon teaser on social media\nDay -1: Email blast to agent network\nDay 0: MLS entry + all platforms go live + social media blitz\nDay 1: Targeted ads begin\nDay 3: First open house\nDay 5: Market feedback report to seller\nDay 7: Strategy review and adjust\n\nAI Prompt: 'Create a complete 7-day listing launch plan for [property] priced at $[X] in [area]. Generate all needed copy: coming soon post, agent email, social posts for days 0, 1, 3, 5, 7, targeted ad copy (Facebook + Instagram), and seller feedback report template. Target buyer: [profile].'" },
      { id: "16-3", title: "ROI Tracking and Business Intelligence", content: "Use AI to track and optimize your business performance:\n\n**Monthly Business Review Prompt:**\n'Here are my numbers for [month]: Leads generated: [X], Showings: [X], Offers written: [X], Closings: [X], Revenue: $[X], Marketing spend: $[X], Time spent on admin: [X] hours.\n\nAnalyze my conversion rates at each stage. Compare to industry averages. Identify my biggest bottleneck. Suggest 3 specific improvements for next month. Calculate my cost per lead, cost per closing, and effective hourly rate.'\n\n**Annual Business Plan:**\nAI Prompt: 'Create a real estate business plan for [year]. Last year's results: [summary]. My goals: [income/transaction targets]. Create a plan that includes: monthly targets, lead generation strategy, marketing budget allocation, systems to build, and skills to develop. Make it actionable with specific weekly activities.'" },
    ],
    quiz: [
      { question: "How long should the AI morning briefing take?", options: ["30 seconds", "5 minutes", "30 minutes", "1 hour"], correct: 1 },
      { question: "When should the 'coming soon' social teaser go out?", options: ["Day of listing", "3 days before", "1 week before", "After first showing"], correct: 1 },
      { question: "What should a monthly business review analyze?", options: ["Only revenue", "Conversion rates at each stage", "Only social media metrics", "Just closing count"], correct: 1 },
      { question: "What's included in the listing launch Day 0 activities?", options: ["Just MLS entry", "MLS + all platforms + social media blitz", "Only the open house", "Agent email only"], correct: 1 },
      { question: "What business metric tells you your biggest growth opportunity?", options: ["Total revenue", "The conversion bottleneck between stages", "Number of social followers", "Years in business"], correct: 1 },
    ]
  },
  {
    id: 17, title: "Certification Assessment", section: "Certification", tier: "premium",
    description: "Complete your final assessment to earn your AI Mastery for Real Estate certificate.",
    lessons: [
      { id: "17-1", title: "Assessment Overview", content: "Congratulations on reaching the final module! Here's what the certification assessment covers:\n\n**Format:** 50 multiple-choice questions + 3 practical tasks\n\n**Topics Covered:**\nAll 16 previous modules, weighted by section:\n- AI Foundations (20%)\n- Essential AI Tools (25%)\n- Real Estate AI Workflows (30%)\n- Advanced AI Strategies (25%)\n\n**Passing Score:** 70% overall\n\n**Practical Tasks:**\n1. Write an AI-assisted listing description using the 5-component formula\n2. Create an AI prompt that generates a client email matching a given voice profile\n3. Design an AI-powered marketing plan for a property launch\n\n**Certificate:** Upon passing, you'll receive a professional AI Mastery for Real Estate certificate with your name, score, and completion date. This certificate can be shared on LinkedIn and included in your marketing materials." },
      { id: "17-2", title: "Study Guide and Key Concepts", content: "Review these key concepts before your assessment:\n\n**Module 1-4 Review:**\n- AI is a tool, not a replacement\n- The RECIPE prompt formula (Role, Example, Context, Instructions, Parameters, Evaluate)\n- Fair Housing compliance with AI (protected classes, safe practices)\n- Data privacy best practices (anonymize before sharing)\n\n**Module 5-8 Review:**\n- 4 email categories (lead response, nurture, transaction, referral)\n- Voice Profile creation and maintenance\n- CMA narrative approach\n- Social media content pillars and calendar strategy\n- The 5-component listing formula\n\n**Module 9-12 Review:**\n- Multi-platform listing optimization\n- 7-touch lead sequence\n- Investment analysis metrics (cap rate, cash-on-cash, GRM)\n- 90-day content calendar creation\n\n**Module 13-16 Review:**\n- Transaction timeline management\n- Brand voice development\n- The 1-to-7 content repurposing method\n- 10-slide listing presentation structure\n- AI morning briefing system\n- Listing launch 7-day sequence" },
      { id: "17-3", title: "Begin Your Assessment", content: "You're ready! Click the quiz button below to begin your 50-question certification assessment.\n\n**Tips for Success:**\n1. Read each question carefully\n2. Think about real-world application, not just theory\n3. Trust your instincts — you've learned this material\n4. You can retake the assessment if needed\n\n**After Passing:**\n- Your certificate will be generated automatically\n- Download and save your certificate PDF\n- Share on LinkedIn with the hashtag #AIRealtorCertified\n- Add it to your email signature and marketing materials\n\n**Remember:** This certification shows clients and colleagues that you're at the forefront of real estate technology. You've invested in your future, and it will pay dividends.\n\nGood luck, and congratulations on completing AI Mastery for Real Estate!" },
    ],
    quiz: [
      { question: "What is the RECIPE prompt formula?", options: ["A cooking technique", "Role, Example, Context, Instructions, Parameters, Evaluate", "Research, Execute, Create, Improve, Publish, Engage", "Read, Edit, Check, Input, Print, Export"], correct: 1 },
      { question: "What is the passing score for certification?", options: ["50%", "60%", "70%", "90%"], correct: 2 },
      { question: "How many content pillars should a social media strategy have?", options: ["2", "5", "8", "12"], correct: 1 },
      { question: "What is the 1-to-7 content method?", options: ["Post 7 times daily", "Transform 1 piece into 7 formats", "Work 1 hour, earn 7 leads", "Create 1 listing, get 7 offers"], correct: 1 },
      { question: "What should you ALWAYS do with AI-generated content?", options: ["Post immediately without review", "Review, edit, and add personal expertise", "Delete it and start from scratch", "Share it only on social media"], correct: 1 },
    ]
  }
];
