-- =============================================
-- Course Content: Property Comparative Analysis
-- Run AFTER 05-add-courses.sql
-- =============================================
-- This populates the "Property Comparative Analysis" course
-- with 6 modules, 18 lessons, and 30 quiz questions.

DO $$
DECLARE
  v_course_id INTEGER;
  v_mod_id INTEGER;
BEGIN

-- Get the course ID
SELECT id INTO v_course_id FROM courses WHERE slug = 'property-comparative-analysis';

IF v_course_id IS NULL THEN
  RAISE EXCEPTION 'Course "property-comparative-analysis" not found. Run 05-add-courses.sql first.';
END IF;

-- Delete existing content for this course (safe re-run)
DELETE FROM quiz_questions WHERE module_id IN (SELECT id FROM course_modules WHERE course_id = v_course_id);
DELETE FROM lessons WHERE module_id IN (SELECT id FROM course_modules WHERE course_id = v_course_id);
DELETE FROM course_modules WHERE course_id = v_course_id;

-- =============================================
-- MODULE 1: Foundations of Property Valuation
-- =============================================
INSERT INTO course_modules (course_id, title, description, sort_order, tier)
VALUES (v_course_id, 'Foundations of Property Valuation', 'Understand the core principles behind property valuation and why accurate pricing is the foundation of every successful real estate transaction.', 1, 'free')
RETURNING id INTO v_mod_id;

INSERT INTO lessons (module_id, title, content, sort_order) VALUES
(v_mod_id, 'Why Accurate Pricing Matters', E'Pricing a property correctly is arguably the single most important skill a real estate agent can master. An overpriced listing sits on the market, accumulates days on market, and ultimately sells for less than it would have if priced correctly from the start. An underpriced property leaves money on the table and can erode client trust. Your ability to determine the right price — and defend it with data — is what separates a trusted advisor from just another agent.\n\nThe **Comparative Market Analysis (CMA)** is your primary tool for pricing. Unlike a formal appraisal, a CMA is prepared by a licensed real estate agent and uses recent comparable sales, active listings, and market trends to estimate a property''s market value. While it does not carry the legal weight of an appraisal, a well-prepared CMA is often more current and more relevant to the local micro-market than a bank-ordered appraisal.\n\nUnderstanding the difference between **market value**, **assessed value**, and **appraised value** is essential. Market value is what a willing buyer will pay a willing seller in an arm''s-length transaction. Assessed value is the number your county uses for tax purposes — it may be significantly higher or lower than market value depending on when the last reassessment occurred. Appraised value is the opinion of a licensed appraiser, typically ordered by a lender. As an agent, your CMA targets market value, and your job is to support that number with solid comparable data.\n\nThe best agents do not just pull numbers — they tell a story with data. When you walk into a listing presentation with a polished CMA that explains why the home is worth what it is, backed by carefully selected comparables and thoughtful adjustments, you earn the client''s confidence before you ever discuss commission.', 1),
(v_mod_id, 'Understanding Market Value vs. Appraised Value', E'One of the most common conversations you will have with clients is explaining why the tax assessment, the Zestimate, or their neighbor''s opinion does not determine what their home is worth. Clients come to the table with preconceived notions about value, and your job is to educate them with facts.\n\n**Market value** is determined by what buyers are actually paying for similar properties in the current market. It is influenced by supply and demand, interest rates, seasonal trends, local employment, school quality, and dozens of other factors. Market value changes constantly — a home worth $350,000 in March might be worth $340,000 in November if buyer demand softens.\n\n**Appraised value** is a licensed appraiser''s opinion of value, typically ordered by a mortgage lender to ensure the property is worth at least as much as the loan amount. Appraisers use comparable sales much like you do in a CMA, but they follow strict guidelines set by USPAP (Uniform Standards of Professional Appraisal Practice). An appraisal can come in above, at, or below the contract price — and when it comes in low, it can derail a deal. Understanding how appraisers think helps you select comparables that will also support the appraised value.\n\n**Assessed value** is set by the county assessor''s office and is used to calculate property taxes. In many jurisdictions, assessed values are updated infrequently and may lag behind the actual market by years. Never use assessed value as a proxy for market value in a CMA — but do be prepared to explain the difference to clients who wonder why their tax bill says one number while your CMA says another.\n\nThe key takeaway for your clients: the market determines value, not an algorithm, not the tax office, and not what the seller wants. Your CMA is the tool that translates market data into a clear, defensible price recommendation.', 2),
(v_mod_id, 'The Anatomy of a CMA Report', E'A professional CMA report is more than a printout from the MLS. It is a presentation piece that demonstrates your market expertise and justifies your pricing recommendation. Here is what every CMA should include:\n\n**Subject Property Details** — Start with a complete profile of the property being valued. Include square footage, lot size, bedroom and bathroom count, year built, condition, upgrades, garage type, and any unique features. Include photos if possible. The more detail you capture here, the more accurate your adjustments will be.\n\n**Comparable Sales (Sold Comps)** — These are the backbone of your CMA. Include 3 to 6 properties that have sold within the last 3 to 6 months, within a reasonable distance (typically 0.5 to 1 mile in urban areas, wider in rural markets), and that are similar in size, style, age, and condition. For each comp, include the sale price, sale date, days on market, price per square foot, and key features. Always note whether any sales involved concessions, as these can distort the true sale price.\n\n**Active Listings** — Current competition matters. Include 2 to 4 active listings that are similar to the subject property. These represent what buyers are comparing your listing against. Note how long they have been on the market — a listing that has been active for 90 days at $400,000 suggests that price point is too high for what it offers.\n\n**Pending Sales** — If available, include 1 to 2 pending sales. These represent the most current market activity. While you may not know the exact contract price, the list price of a recently pending property gives you a strong signal about where the market is heading.\n\n**Adjustment Grid** — This is where your expertise shows. Create a grid that compares each comp to the subject property and makes dollar adjustments for differences in square footage, lot size, bedroom count, bathroom count, garage, condition, and upgrades. We will cover adjustment methodology in detail in the next module.\n\n**Market Trends Summary** — Include a brief analysis of local market trends: median price changes over the past 6 to 12 months, average days on market, months of inventory, and list-to-sale price ratio. This context helps your client understand whether the market is favoring buyers or sellers.\n\n**Price Recommendation** — End with a clear recommended list price or price range, supported by the data you have presented. A range of $5,000 to $10,000 gives the seller flexibility while keeping expectations realistic.', 3);

INSERT INTO quiz_questions (module_id, question, options, correct_answer, sort_order) VALUES
(v_mod_id, 'What is the primary purpose of a Comparative Market Analysis (CMA)?', '["To determine the assessed value for property taxes", "To estimate the market value of a property using comparable sales data", "To calculate the insurance replacement cost of a property", "To determine the exact appraised value for a lender"]', 1, 1),
(v_mod_id, 'Which type of value is determined by what buyers are currently paying for similar properties?', '["Assessed value", "Insured value", "Market value", "Replacement value"]', 2, 2),
(v_mod_id, 'How many comparable sold properties should typically be included in a CMA?', '["1 to 2", "3 to 6", "8 to 10", "At least 12"]', 1, 3),
(v_mod_id, 'Why should assessed value NOT be used as a proxy for market value?', '["Because assessed values are always higher than market value", "Because assessed values may be updated infrequently and can lag behind the market", "Because assessed values include the value of personal property", "Because assessed values are only used for commercial properties"]', 1, 4),
(v_mod_id, 'What do active listings in a CMA represent?', '["The historical sales trend in the neighborhood", "Properties that failed to sell and were withdrawn", "The current competition a listing will face from buyers perspective", "The maximum possible value for the subject property"]', 2, 5);


-- =============================================
-- MODULE 2: Selecting the Right Comparables
-- =============================================
INSERT INTO course_modules (course_id, title, description, sort_order, tier)
VALUES (v_course_id, 'Selecting the Right Comparables', 'Learn how to identify, filter, and select the most relevant comparable sales to build a defensible CMA that withstands client scrutiny and appraiser review.', 2, 'free')
RETURNING id INTO v_mod_id;

INSERT INTO lessons (module_id, title, content, sort_order) VALUES
(v_mod_id, 'The Three Pillars of Comparable Selection', E'Selecting the right comparables is the most critical step in building an accurate CMA. Choose the wrong comps and your entire analysis is unreliable — no amount of adjustment math can fix a fundamentally flawed comp selection. There are three pillars that guide every comp selection decision: **proximity**, **recency**, and **similarity**.\n\n**Proximity** refers to how close the comparable is to the subject property. In most urban and suburban markets, you want comps within 0.5 to 1 mile. In rural areas, you may need to expand to 3 to 5 miles. The key principle is that the comp should be in the same market area — ideally the same subdivision, school zone, or neighborhood. A home two blocks away in the same subdivision is almost always a better comp than a home one mile away in a different neighborhood, even if the distant home is more similar in features.\n\n**Recency** means using the most current sales data available. In a stable market, sales within the past 6 months are ideal. In a rapidly changing market — whether rising or falling — you may want to limit comps to the past 3 months. The more recent the sale, the more accurately it reflects current market conditions. Be cautious with older sales — if prices have been rising at 5% per year, a sale from 12 months ago understates current value by that amount unless you make a time adjustment.\n\n**Similarity** covers the physical characteristics of the property: square footage, lot size, bedroom and bathroom count, year built, architectural style, condition, and features. The ideal comp matches the subject on as many of these factors as possible. A 2,200 square foot ranch built in 1995 is a better comp for a similar subject than a 3,500 square foot two-story built in 2015, even if both are in the same subdivision.\n\nWhen these three pillars conflict — as they often do — prioritize proximity and recency over similarity. You can adjust for differences in square footage or features, but you cannot adjust for being in a fundamentally different market area.', 1),
(v_mod_id, 'Common Comp Selection Mistakes', E'Even experienced agents make comp selection errors that weaken their CMAs. Here are the most common mistakes and how to avoid them.\n\n**Cherry-picking comps to hit a target price.** This is the cardinal sin of CMA preparation. If a seller wants $450,000 and you only select comps that support that number while ignoring lower sales, you are doing your client a disservice. A CMA should reflect reality, not wishful thinking. Include the best available comps regardless of where they point, and let the data tell the story.\n\n**Using comps from a different neighborhood or school district.** Neighborhood boundaries and school zones can create significant value differences between properties that are geographically close. A home on the east side of a street might be in a different school district than one on the west side, and that difference can mean $20,000 or more in value. Always verify that your comps are in the same effective market area.\n\n**Ignoring sale concessions.** A sale at $400,000 where the seller paid $15,000 in closing costs is really a $385,000 sale in terms of market value. Concessions inflate the recorded sale price and can mislead your analysis. Check the MLS remarks and agent notes for concessions, and adjust accordingly.\n\n**Relying too heavily on price per square foot.** Price per square foot is a useful screening tool, but it should never be the primary basis for your valuation. A 1,200 square foot home will almost always have a higher price per square foot than a 2,400 square foot home in the same area, even if the larger home is worth more overall. Use price per square foot to identify outliers and sanity-check your analysis, not as your primary valuation method.\n\n**Using too few or too many comps.** Three to six sold comps is the sweet spot. Fewer than three does not give you enough data to establish a trend. More than six creates noise — you end up including marginal comps that weaken your analysis. Select the best available comps and build your case around quality, not quantity.', 2),
(v_mod_id, 'Handling Unique Properties with Limited Comps', E'Not every property fits neatly into a box. Waterfront homes, properties with acreage, historic homes, multi-generational designs, and properties with unusual features all present comp selection challenges. Here is how to handle these situations.\n\n**Expand your search radius gradually.** Start with the tightest parameters — same subdivision, last 3 months, similar size. If that yields no comps, expand one parameter at a time. First extend the time frame to 6 months, then 12 months. Then widen the geographic area. Then broaden the size range. Track which parameter you expanded and by how much so you can explain your reasoning.\n\n**Use bracketing.** When you cannot find identical comps, find properties that bracket the subject — one that is clearly inferior and one that is clearly superior. If a 4,000 square foot lakefront home has no direct comps, find a 3,200 square foot lakefront that sold for $550,000 and a 4,800 square foot lakefront that sold for $750,000. The subject likely falls somewhere in between, and you can use adjustments to narrow the range.\n\n**Separate land value from improvement value.** For properties on large lots or with significant acreage, it can be helpful to value the land and the improvements separately. Use vacant land sales to establish a per-acre value for the land, then compare the improvements (house, garage, outbuildings) to similar structures on standard lots. This two-part approach often yields a more reliable estimate than trying to find a single comp that matches both the house and the land.\n\n**Consider the cost approach as a sanity check.** For newer or highly custom homes, estimate the replacement cost of the improvements (using cost-per-square-foot data from local builders), subtract depreciation based on age and condition, then add the land value. This gives you an alternative valuation that can confirm or challenge your comparable sales approach.\n\n**Document everything.** When comps are limited, your CMA needs extra explanation. Add narrative comments explaining why you selected each comp, what adjustments you made, and what limitations exist in the data. Transparency builds trust — clients and appraisers respect an agent who acknowledges data limitations rather than glossing over them.', 3);

INSERT INTO quiz_questions (module_id, question, options, correct_answer, sort_order) VALUES
(v_mod_id, 'What are the three pillars of comparable selection?', '["Price, condition, and location", "Proximity, recency, and similarity", "Size, age, and features", "Neighborhood, school district, and tax rate"]', 1, 1),
(v_mod_id, 'When proximity, recency, and similarity conflict, which should generally be prioritized?', '["Similarity over everything else", "Recency over proximity", "Proximity and recency over similarity", "All three should be weighted equally"]', 2, 2),
(v_mod_id, 'What is the cardinal sin of CMA preparation?', '["Using too many comparable properties", "Cherry-picking comps to hit a target price", "Including active listings in the report", "Using properties from the same subdivision"]', 1, 3),
(v_mod_id, 'What technique involves finding one inferior and one superior comp to establish a value range?', '["Price anchoring", "Regression analysis", "Bracketing", "Paired sales analysis"]', 2, 4),
(v_mod_id, 'How should an agent handle sale concessions when selecting comps?', '["Ignore them since they are standard practice", "Add the concession amount to the sale price", "Adjust the effective sale price downward to account for concessions", "Exclude any sale that included concessions"]', 2, 5);


-- =============================================
-- MODULE 3: Making Accurate Adjustments
-- =============================================
INSERT INTO course_modules (course_id, title, description, sort_order, tier)
VALUES (v_course_id, 'Making Accurate Adjustments', 'Master the art and science of adjusting comparable sales for differences in features, condition, and location to arrive at an accurate value estimate.', 3, 'premium')
RETURNING id INTO v_mod_id;

INSERT INTO lessons (module_id, title, content, sort_order) VALUES
(v_mod_id, 'The Adjustment Process Explained', E'No two properties are identical, which is why adjustments are necessary. The adjustment process takes each comparable sale and modifies its sale price to account for differences between the comp and the subject property. The adjusted price tells you what the comp would have sold for if it were identical to the subject.\n\n**The golden rule of adjustments: you always adjust the comp to the subject, never the subject to the comp.** If the comp has a feature the subject does not (like a pool), you subtract value from the comp''s sale price. If the subject has a feature the comp does not, you add value to the comp''s sale price. This can feel counterintuitive at first, but it makes sense when you remember the goal: you want to know what a property like the subject would sell for.\n\n**Common adjustment categories include:**\n- Square footage (typically $50 to $150 per square foot depending on the market)\n- Lot size (varies widely; minimal impact in subdivisions with standard lots)\n- Bedroom count ($5,000 to $15,000 per bedroom depending on market)\n- Bathroom count ($5,000 to $15,000 per bathroom)\n- Garage (single vs. double, attached vs. detached)\n- Condition and updates (kitchen remodel, roof age, HVAC age)\n- Pool ($10,000 to $30,000 depending on region)\n- Basement (finished vs. unfinished, walk-out vs. standard)\n- Age of property (newer homes command premiums)\n- Location within the neighborhood (busy road vs. cul-de-sac, backing to park vs. commercial)\n\n**Keep your total net adjustment under 15% of the comp''s sale price and gross adjustments under 25%.** If your adjustments exceed these thresholds, the comp is too different from the subject and should probably be replaced with a better match. Excessive adjustments reduce reliability and invite scrutiny from appraisers and clients alike.', 1),
(v_mod_id, 'Determining Adjustment Values Using Paired Sales', E'The most reliable way to determine how much a specific feature is worth is through **paired sales analysis**. This technique compares two properties that are nearly identical except for one feature, and the difference in their sale prices represents the market value of that feature.\n\n**Example:** Two homes in the same subdivision sold within a month of each other. Both are 3-bedroom, 2-bathroom ranches built in 2005 with approximately 1,800 square feet. Home A has a 2-car garage and sold for $325,000. Home B has a 3-car garage and sold for $338,000. The difference of $13,000 suggests the market values the additional garage bay at approximately $13,000 in this area.\n\nTo use paired sales effectively, look for properties that match on as many characteristics as possible. The more controlled the comparison (fewer differences), the more reliable the implied adjustment value. In practice, finding a perfect pair is rare, so you may need to analyze multiple pairs and average the results to establish a reliable adjustment amount.\n\n**Sources for adjustment data include:**\n- Your own paired sales analysis from MLS data\n- Local appraiser guidelines or cost manuals\n- Marshall and Swift cost data (used by many appraisers)\n- Conversations with local appraisers about typical adjustments in your market\n- Builder upgrade pricing (useful for estimating the value of specific features like granite countertops, hardwood floors, or upgraded appliances)\n\n**Important caveat:** Adjustment values vary by market and price range. A pool might add $25,000 of value in a $500,000 neighborhood but only $10,000 in a $200,000 neighborhood. A fourth bedroom adds more value when the surrounding area has few 4-bedroom homes than when 4-bedrooms are the norm. Always calibrate your adjustments to the specific market and price point you are working in.\n\nKeep a running log of the adjustment values you develop through paired sales analysis. Over time, this becomes your personal adjustment database — a competitive advantage that makes your CMAs faster and more accurate.', 2),
(v_mod_id, 'Condition and Quality Adjustments', E'Condition and quality adjustments are the most subjective part of a CMA, and they are often where agents make the biggest errors. A home that has been completely renovated with high-end finishes is not comparable to a home of the same size and age that still has original 1990s fixtures — yet they may look identical on a feature-by-feature comparison in the MLS.\n\n**Establish a condition rating system.** The appraisal industry uses a standardized rating scale from C1 (brand new) to C6 (major repairs needed). While you do not need to use this exact scale, developing a consistent framework helps you make objective assessments. A simple 5-point scale works well: Excellent (fully renovated with high-end finishes), Good (well-maintained with some updates), Average (functional but showing age), Fair (needs cosmetic updates), Poor (needs significant work).\n\n**Kitchen and bathroom updates have the biggest impact.** A full kitchen remodel in a mid-range home might add $15,000 to $30,000 in value. Updated bathrooms add $5,000 to $15,000 each. However, the value added depends on what is typical for the neighborhood. If every home in the subdivision has been updated, a renovated kitchen is expected, not a premium. Conversely, in a neighborhood where most homes are original, an updated home stands out and commands a significant premium.\n\n**Mechanical systems matter too.** A new roof ($8,000 to $15,000 value), new HVAC system ($5,000 to $10,000), or new water heater ($1,000 to $2,000) may not be visible, but buyers and appraisers account for them. If a comp had a 20-year-old roof when it sold and the subject has a new roof, that difference warrants an adjustment.\n\n**Deferred maintenance is a negative adjustment.** If the subject property needs work, you need to account for the cost of those repairs in your valuation. A home needing a new roof, new carpet, and exterior paint might require $25,000 to $35,000 in deferred maintenance adjustments. Be transparent with your seller about these factors — they affect not only your list price recommendation but also how the property will appraise.', 3);

INSERT INTO quiz_questions (module_id, question, options, correct_answer, sort_order) VALUES
(v_mod_id, 'When making adjustments in a CMA, what is the golden rule?', '["Always adjust the subject property to match each comp", "Always adjust the comp to the subject property", "Adjust whichever property has fewer features", "Only adjust for square footage differences"]', 1, 1),
(v_mod_id, 'What is paired sales analysis?', '["Comparing two identical properties in different markets", "Comparing two nearly identical properties that differ in one feature to determine that features value", "Pairing each comp with the subject for a side-by-side comparison", "Analyzing sales that occurred on the same date"]', 1, 2),
(v_mod_id, 'What is the recommended maximum net adjustment as a percentage of the comp sale price?', '["5%", "10%", "15%", "25%"]', 2, 3),
(v_mod_id, 'Which home improvements typically have the biggest impact on value?', '["Landscaping and exterior paint", "Kitchen and bathroom updates", "New garage doors and driveways", "Interior paint and carpet"]', 1, 4),
(v_mod_id, 'If a comparable has a pool but the subject property does not, how should you adjust?', '["Add the value of the pool to the comp price", "Subtract the value of the pool from the comp price", "Make no adjustment since pools are personal preference", "Add half the pool value as a compromise"]', 1, 5);


-- =============================================
-- MODULE 4: Market Trends and Data Analysis
-- =============================================
INSERT INTO course_modules (course_id, title, description, sort_order, tier)
VALUES (v_course_id, 'Market Trends and Data Analysis', 'Learn to read and interpret market data, identify trends, and incorporate macro and micro market conditions into your property valuation.', 4, 'premium')
RETURNING id INTO v_mod_id;

INSERT INTO lessons (module_id, title, content, sort_order) VALUES
(v_mod_id, 'Key Market Metrics Every Agent Should Track', E'Understanding market trends adds depth and credibility to your CMA. A price recommendation backed by trend data is far more persuasive than one based solely on comparable sales. Here are the key metrics you should track and understand.\n\n**Median Sale Price** is the midpoint of all sales in a given area and time period — half sold for more, half sold for less. Track this monthly and compare year-over-year. A rising median suggests appreciation; a falling median suggests depreciation. Be cautious about reading too much into a single month — look for trends over 3 to 6 months.\n\n**Average Days on Market (DOM)** tells you how quickly homes are selling. Low DOM (under 20 days) indicates a seller''s market with high demand. High DOM (over 60 days) suggests a buyer''s market where inventory is sitting. Track DOM for your specific price range and area, not just the overall market — a $200,000 home may sell in 10 days while a $600,000 home in the same zip code takes 45 days.\n\n**Months of Supply** (also called absorption rate) measures how long it would take to sell all current listings at the current pace of sales. Under 4 months is generally a seller''s market, 4 to 6 months is balanced, and over 6 months is a buyer''s market. This metric helps you advise clients on pricing strategy — in a seller''s market with 2 months of supply, pricing at or slightly above the last comp may be justified. In a buyer''s market with 8 months of supply, pricing below the last comp might be necessary to attract offers.\n\n**List-to-Sale Price Ratio** shows the relationship between what sellers are asking and what buyers are paying. A ratio of 98% means homes are selling for 2% below list price on average. A ratio above 100% means multiple offers are pushing prices above asking. This metric helps you set realistic expectations — if the average ratio is 97%, pricing at $400,000 means expecting offers around $388,000.\n\n**New Listings vs. Closed Sales** — when new listings outpace closings, inventory is growing and the market is softening. When closings outpace new listings, inventory is shrinking and competition among buyers increases. Watch this ratio monthly to anticipate market shifts before they show up in median prices.', 1),
(v_mod_id, 'Micro-Market Analysis: Neighborhood-Level Trends', E'Broad market statistics tell part of the story, but real estate is hyper-local. The trends in one neighborhood can be dramatically different from trends in a subdivision just two miles away. Your CMA should reflect the micro-market, not just the macro-market.\n\n**Define your micro-market carefully.** A micro-market might be a specific subdivision, a section of a zip code, a school attendance zone, or a neighborhood bounded by major roads. The key is that properties within the micro-market compete with each other for the same buyers. When you pull comps, your micro-market definition determines your search boundaries.\n\n**Track subdivision-specific trends.** If you are preparing a CMA for a home in Oakwood Estates, pull the last 12 months of sales in Oakwood Estates specifically. Calculate the median price, average DOM, and list-to-sale ratio for that subdivision alone. You may find that Oakwood Estates has appreciated 8% while the broader zip code only appreciated 4% — that subdivision-specific data makes your CMA more accurate and more impressive to the client.\n\n**Watch for neighborhood catalysts.** New development (positive or negative), school redistricting, new highway access, commercial development, and crime trends can all shift neighborhood values independently of the broader market. If a new Trader Joe''s is opening two blocks from your listing, that is a positive catalyst worth mentioning. If a major employer in the area announced layoffs, that is a headwind to acknowledge.\n\n**Seasonality affects micro-markets differently.** In a family-oriented subdivision near top-rated schools, spring and summer are peak seasons and prices reflect that. In a downtown condo market, seasonality may be less pronounced. Understand the seasonal patterns of your specific micro-market and factor them into your pricing recommendation.\n\n**Present the micro-market story in your CMA.** Add a section titled "Neighborhood Market Summary" that includes 3 to 5 bullet points about recent trends specific to the area. This demonstrates local expertise that automated tools like Zestimates cannot replicate — and it is one of the strongest differentiators you can offer as a listing agent.', 2),
(v_mod_id, 'Using Technology for Market Analysis', E'Modern technology tools can dramatically speed up your market analysis and help you present data in compelling ways. Here are the platforms and techniques every agent should know.\n\n**MLS statistical tools** are your first stop. Most MLS systems include built-in reporting tools that can generate average price, DOM, absorption rate, and price-per-square-foot data for any area and time period you define. Learn to use your MLS''s statistical reporting features — many agents never explore beyond basic property searches, but the stats tools are powerful and underutilized.\n\n**Cloud CMA and similar platforms** allow you to create polished, client-facing CMA reports with professional formatting, charts, and neighborhood data. These tools pull data directly from the MLS and format it into a presentation that looks far more professional than a stack of MLS printouts. Many also include market trend charts that automatically update.\n\n**Redfin and Zillow data** can supplement your MLS analysis, particularly for market trend data and price history charts. While you should never rely on automated valuations for your pricing recommendation, these platforms provide useful visualizations and trend data that can enhance your CMA presentation. Use them as supplements, not substitutes.\n\n**RPR (Realtors Property Resource)** is a free NAR member benefit that provides detailed property data, neighborhood demographics, school information, and market trends. RPR reports are professional-looking and include data points not available in the MLS, such as refined value estimates, distressed property data, and demographic profiles. Many agents overlook this free tool.\n\n**Spreadsheet analysis** is essential for serious CMA work. Create a template in Google Sheets or Excel that calculates adjustments automatically when you input comp data. A well-designed spreadsheet lets you plug in comp details and instantly see the adjusted values, average adjusted price, and recommended price range. Once you build the template, you can prepare a detailed CMA in 30 minutes instead of 2 hours.', 3);

INSERT INTO quiz_questions (module_id, question, options, correct_answer, sort_order) VALUES
(v_mod_id, 'What does "months of supply" measure?', '["The average time a home takes to sell after listing", "How long it would take to sell all current listings at the current pace of sales", "The number of months since prices last increased", "How many months of mortgage payments the average buyer can afford"]', 1, 1),
(v_mod_id, 'In general, what months of supply indicates a sellers market?', '["Under 4 months", "4 to 6 months", "6 to 8 months", "Over 8 months"]', 0, 2),
(v_mod_id, 'What is a micro-market in real estate?', '["The market for homes under $100,000", "A specific subdivision or neighborhood that competes for the same buyers", "The market for micro-apartments and tiny homes", "An online marketplace for real estate leads"]', 1, 3),
(v_mod_id, 'What does a list-to-sale price ratio above 100% indicate?', '["Homes are selling below asking price", "The market is declining", "Homes are selling above asking price due to competition", "Sellers are overpricing their listings"]', 2, 4),
(v_mod_id, 'Which free NAR member benefit provides detailed property data, demographics, and market trends?', '["Zillow Premier Agent", "Cloud CMA", "RPR (Realtors Property Resource)", "HomeSnap Pro"]', 2, 5);


-- =============================================
-- MODULE 5: Presenting Your CMA with Confidence
-- =============================================
INSERT INTO course_modules (course_id, title, description, sort_order, tier)
VALUES (v_course_id, 'Presenting Your CMA with Confidence', 'Transform your CMA from a data report into a persuasive presentation that wins listings and earns client trust.', 5, 'premium')
RETURNING id INTO v_mod_id;

INSERT INTO lessons (module_id, title, content, sort_order) VALUES
(v_mod_id, 'Structuring Your Listing Presentation Around the CMA', E'The CMA is not just a document — it is the centerpiece of your listing presentation. How you present the data matters as much as the data itself. A confident, well-structured presentation positions you as the market expert and sets realistic pricing expectations from the start.\n\n**Open with the market story, not the number.** Before you reveal your price recommendation, set the context. Share 2 to 3 key market trends: "Homes in Oakwood Estates have appreciated 6% over the past year. The average home is selling in 14 days, and most are getting within 2% of asking price. This is one of the strongest seller''s markets we have seen in this neighborhood in the past 5 years." This context makes your eventual price recommendation feel inevitable rather than arbitrary.\n\n**Walk through the comps one by one.** Do not just hand over a stack of printouts. Show each comparable on a screen or tablet, point out the similarities and differences with the subject property, and explain your adjustments in plain language. "This home on Elm Street is very similar to yours — same floor plan, same lot size. It sold for $385,000 two months ago. The main difference is that it had an updated kitchen while yours still has the original. Based on what kitchen updates are worth in this market, I adjusted for that difference, which brings the adjusted value to $370,000."\n\n**Show the range before the recommendation.** After walking through all comps, summarize the adjusted values in a range: "After adjusting for differences, the comparable sales suggest a market value between $365,000 and $385,000 for your home." Then make your specific recommendation within that range and explain why: "Based on the condition of your home and the current competition, I recommend listing at $379,900. This positions you competitively against the two active listings while leaving room for negotiation."\n\n**Address the Zestimate proactively.** Most sellers have looked at their Zestimate before you arrive. Acknowledge it: "You may have seen online estimates for your home. Those tools use algorithms that cannot account for your specific updates, the condition of your home, or the nuances of this neighborhood. My analysis is based on actual sales of similar homes in your area, with adjustments for the specific differences." This positions your expertise against the algorithm without being dismissive of the client''s research.', 1),
(v_mod_id, 'Handling Seller Objections to Your Price', E'Even the best CMA will face pushback from sellers who believe their home is worth more. Handling these objections professionally and empathetically is essential to winning the listing at the right price.\n\n**"Our neighbor sold for more."** This is the most common objection. Ask for details: "Which neighbor? When did it sell?" Then pull up that sale and compare it to the subject. Often the neighbor''s home had features the seller''s does not — more square footage, a remodeled kitchen, a larger lot. Walk through the differences: "The Johnsons'' home did sell for $410,000, but it also has 300 more square feet and a completely remodeled kitchen. When we adjust for those differences, it actually supports our estimate for your home."\n\n**"We need to net a certain amount."** Sellers often work backward from their desired net proceeds. Acknowledge their financial goals with empathy, then redirect to market reality: "I understand you would like to net $350,000 after paying off your mortgage and closing costs. I want to help you achieve the best possible result. However, buyers determine value based on comparable sales, not our financial needs. If we price above what the market supports, the home will sit, and we will likely end up selling for less than if we had priced it correctly from the start."\n\n**"We are not in a hurry."** Some sellers believe that time on market does not matter because they can wait for the right buyer. Explain the cost of overpricing: "I understand there is no rush. However, the data shows that the most buyer interest occurs in the first two weeks after listing. A home priced correctly generates multiple showings and often competing offers during that window. Once a listing has been on the market for 30 or 60 days, buyers begin to wonder what is wrong with it, and the price often ends up lower than if we had started competitively."\n\n**"We put $50,000 into renovations."** Not all improvements return dollar-for-dollar value. Educate the seller: "Your renovations have definitely enhanced your home and will help it sell faster. However, home improvements typically return 50% to 80% of their cost in resale value. The updated kitchen is absolutely reflected in my pricing — without it, I would recommend $15,000 less. But the market does not give full credit for every dollar spent on improvements."', 2),
(v_mod_id, 'Using Your CMA for Buyer Consultations', E'CMAs are not just for listing appointments — they are equally powerful when working with buyers. A buyer-focused CMA helps your clients make competitive offers, avoid overpaying, and understand the true market value of homes they are interested in.\n\n**Pre-offer analysis.** When a buyer wants to make an offer, prepare a quick CMA for that property. Pull the 3 best comparable sales, make basic adjustments, and show your buyer where the asking price falls relative to market value. "Based on recent sales of similar homes in this area, the market supports a value between $340,000 and $355,000. The asking price of $359,000 is about 3% above the upper end of that range. I recommend starting our offer at $348,000 with room to negotiate up to $355,000." This data-driven approach helps buyers feel confident in their offer strategy.\n\n**Competing offer situations.** In a multiple-offer scenario, your CMA becomes even more critical. Help your buyer understand the maximum they should pay based on market data, separate from the emotional pressure of competition. "The comps support a maximum value of $360,000. If we offer $370,000 to beat other offers, you should know that the appraisal may come in below the contract price, and you may need to bring additional cash to closing or renegotiate." Informed buyers make better decisions.\n\n**Post-inspection negotiations.** After an inspection reveals issues, your CMA helps quantify the impact. If the inspection finds a 15-year-old roof that needs replacement, you can show that comparable sales with newer roofs sold for $10,000 to $12,000 more than those with aging roofs. This gives your repair request or price reduction a factual basis rather than appearing arbitrary.\n\n**Educating first-time buyers.** Many first-time buyers do not understand how market value is determined. Walk them through a simplified CMA early in the process so they understand why a home priced at $300,000 might actually be worth $310,000 (and why they should act fast) or only $280,000 (and why they should negotiate). This education builds trust and positions you as their advisor, not just their search engine.', 3);

INSERT INTO quiz_questions (module_id, question, options, correct_answer, sort_order) VALUES
(v_mod_id, 'What should you present BEFORE revealing your price recommendation in a listing presentation?', '["Your commission rate", "The market context and trends", "The list of things the seller needs to fix", "Competing agent proposals"]', 1, 1),
(v_mod_id, 'When a seller says their neighbor sold for more, what is the best response approach?', '["Agree and raise your price recommendation", "Tell them their neighbor was lucky", "Pull up that sale and compare features showing the differences that explain the price gap", "Suggest they hire the neighbors agent instead"]', 2, 2),
(v_mod_id, 'What percentage of their cost do home improvements typically return in resale value?', '["100%", "90 to 95%", "50 to 80%", "25 to 40%"]', 2, 3),
(v_mod_id, 'How can a CMA help buyers in a multiple-offer situation?', '["It tells them exactly what to offer", "It helps them understand the maximum value supported by market data so they do not overpay", "It guarantees the appraisal will come in at the offer price", "It eliminates the need for an appraisal"]', 1, 4),
(v_mod_id, 'Why is a CMA useful during post-inspection negotiations?', '["It replaces the need for a home inspection", "It provides a factual basis for repair requests or price reductions", "It guarantees the seller will accept a lower price", "It determines exactly how much repairs will cost"]', 1, 5);


-- =============================================
-- MODULE 6: Advanced CMA Techniques and Special Situations
-- =============================================
INSERT INTO course_modules (course_id, title, description, sort_order, tier)
VALUES (v_course_id, 'Advanced CMA Techniques and Special Situations', 'Handle complex valuation scenarios including multi-family properties, new construction, estate sales, and investment property analysis.', 6, 'premium')
RETURNING id INTO v_mod_id;

INSERT INTO lessons (module_id, title, content, sort_order) VALUES
(v_mod_id, 'Multi-Family and Income Property Analysis', E'Valuing multi-family and income-producing properties requires a different approach than single-family residential. While comparable sales still matter, income and expense analysis becomes the primary valuation driver for serious investors.\n\n**The Income Approach** values a property based on the income it generates. The basic formula is: Net Operating Income (NOI) divided by the Capitalization Rate (Cap Rate) equals Value. If a duplex generates $36,000 per year in rental income and has $12,000 in annual expenses, the NOI is $24,000. If the prevailing cap rate for similar properties in the area is 6%, the estimated value is $24,000 / 0.06 = $400,000.\n\n**Calculating NOI accurately** requires accounting for all income and all expenses. Income includes rent from all units, laundry income, parking fees, and any other revenue. Expenses include property taxes, insurance, maintenance, management fees (even if owner-managed — use 8% to 10% as a standard), vacancy allowance (typically 5% to 8%), repairs, utilities paid by the owner, and capital reserves. Do NOT include mortgage payments in the expense calculation — NOI is calculated before debt service.\n\n**Cap rates vary by market, property type, and condition.** A newer duplex in a desirable area might trade at a 5% cap rate, while an older fourplex in a transitional neighborhood might require an 8% cap rate. Research local cap rates by analyzing recent multi-family sales in your area. Your MLS, CoStar, or local investor groups are good sources for this data.\n\n**For small multi-family (2 to 4 units)**, use both the comparable sales approach and the income approach, then reconcile the two. If the sales approach suggests $380,000 and the income approach suggests $400,000, the true value likely falls in between. For larger properties (5+ units), the income approach is the primary valuation method.\n\n**Gross Rent Multiplier (GRM)** is a simpler screening tool: Sale Price divided by Annual Gross Rent. If similar duplexes sell for 10 to 12 times their annual gross rent, you can quickly estimate whether a property is priced reasonably. However, GRM does not account for expenses, so it should supplement — not replace — a full income analysis.', 1),
(v_mod_id, 'New Construction and Pre-Sale Valuation', E'Valuing new construction presents unique challenges because the home may not exist yet — or it may be partially built with no directly comparable finished product in the area. Here is how to approach these situations.\n\n**Builder pricing is not market value.** A builder sets prices based on construction costs plus profit margin, marketing conditions, and inventory levels. These prices may be above or below market value depending on the builder''s situation. A spec home that has been sitting unsold for 6 months may be priced above what the market will bear, while a popular floor plan in a high-demand community may sell for more than the builder''s base price with upgrades.\n\n**Use resale comps when available.** If the subdivision has been established long enough to have resales, those resale prices are your best comparable data. A home that was purchased from the builder for $380,000 two years ago and resold today for $395,000 tells you more about current market value than the builder''s current price list.\n\n**For brand-new subdivisions with no resales**, compare to similar new construction in nearby subdivisions. Look for builders offering similar quality levels, square footage ranges, and lot sizes. If a competing builder two miles away is selling comparable homes for $350,000 to $375,000, that establishes the market range.\n\n**Account for builder incentives and concessions.** Builders frequently offer incentives such as closing cost credits, free upgrades, rate buydowns, or design center credits. A home listed at $400,000 with $20,000 in incentives has an effective price of $380,000. These concessions should be factored into your comparable analysis.\n\n**The cost approach is particularly useful for new construction.** Estimate the land value using recent lot sales in the area, then add the estimated construction cost (local builders can provide cost-per-square-foot estimates for various quality levels). This gives you an independent check against the builder''s asking price and the comparable sales data.\n\n**Pre-sale considerations for buyers.** When a buyer is purchasing a to-be-built home, help them understand that the final appraised value may differ from the contract price, especially if the market shifts during the 6 to 12 month construction period. Recommend that buyers include an appraisal contingency and budget for potential gaps between the appraised value and the purchase price.', 2),
(v_mod_id, 'Estate Sales, Divorce, and Distressed Situations', E'Special circumstances affect both the sale process and the valuation. Understanding these situations helps you advise clients accurately and avoid pricing pitfalls.\n\n**Estate sales** often involve properties that have been owner-occupied for decades with deferred maintenance and dated finishes. The personal representative (executor) may have an emotional attachment or unrealistic expectations based on the decedent''s opinion of value. Your CMA needs to honestly reflect the property''s current condition, not what it might be worth after $50,000 in updates. Present comparables that are similar in condition, and if none exist, use updated comps with a significant negative condition adjustment. Be transparent: "The comparable sales in updated condition sold for $375,000 to $390,000. Given that your property needs approximately $30,000 to $40,000 in updates, I recommend pricing at $340,000 to $350,000 to attract buyers willing to take on renovations."\n\n**Divorce situations** require extra sensitivity and sometimes two separate CMAs — one for each party. Pricing must be objective and defensible because attorneys and sometimes courts will scrutinize your analysis. Stick strictly to the data, avoid advocacy for either side, and document your methodology thoroughly. If both parties hire different agents who arrive at significantly different values, the comparable data should overlap — the dispute is usually about subjective adjustments, not the underlying sales data.\n\n**Distressed sales and short sales** may need to account for the property''s condition and the seller''s urgency. A property being sold in a short sale or pre-foreclosure may be in below-average condition and may need to be priced for a quick sale. Use standard comps but apply a condition adjustment if warranted. Do not automatically assume distressed sales require a discount — if the property is in good condition, price it at market value. The seller''s financial situation does not change the property''s market value.\n\n**Relocation sales** sometimes involve corporate relocation companies that order their own appraisals or CMAs. If you are hired by a relocation company, follow their specific CMA guidelines carefully — they typically have strict formatting requirements and adjustment rules. If your recommended price differs significantly from the relocation company''s internal valuation, prepare a detailed explanation supported by the strongest possible comparable data.', 3);

INSERT INTO quiz_questions (module_id, question, options, correct_answer, sort_order) VALUES
(v_mod_id, 'What is the basic formula for the income approach to valuation?', '["Sale Price minus Expenses equals Value", "NOI divided by Cap Rate equals Value", "Gross Rent multiplied by 12 equals Value", "Purchase Price plus Improvements equals Value"]', 1, 1),
(v_mod_id, 'Should mortgage payments be included when calculating Net Operating Income?', '["Yes, they are the largest expense", "Only for investment properties", "No, NOI is calculated before debt service", "Only if the owner occupies one unit"]', 2, 2),
(v_mod_id, 'Why is builder pricing NOT the same as market value?', '["Builder prices are always higher than market value", "Builder prices are based on cost plus profit margin and may be above or below market value", "Builder prices do not include land value", "Builder prices are set by appraisers"]', 1, 3),
(v_mod_id, 'When preparing a CMA for an estate sale with deferred maintenance, what is the best approach?', '["Price based on what the home would be worth if it were updated", "Use comparable sales in similar condition or adjust updated comps for the condition difference", "Price at assessed value since the owner is deceased", "Refuse the listing since the home needs too much work"]', 1, 4),
(v_mod_id, 'What special consideration applies to CMAs prepared for divorce situations?', '["Price should favor the party who hired you", "Pricing must be objective and defensible since attorneys and courts may review it", "Only one CMA should be prepared for both parties", "The CMA should include the cost of hiring a divorce attorney"]', 1, 5);

RAISE NOTICE 'Property Comparative Analysis course content inserted successfully!';
RAISE NOTICE 'Modules: 6, Lessons: 18, Quiz Questions: 30';

END $$;
