-- =============================================
-- Course Content: Real Estate Tools Training
-- Run AFTER 05-add-courses.sql
-- =============================================
-- This populates the "Real Estate Tools Training" course
-- with 6 modules, 18 lessons, and 30 quiz questions.

DO $$
DECLARE
  v_course_id INTEGER;
  v_mod1 INTEGER;
  v_mod2 INTEGER;
  v_mod3 INTEGER;
  v_mod4 INTEGER;
  v_mod5 INTEGER;
  v_mod6 INTEGER;
BEGIN

-- Get the course ID
SELECT id INTO v_course_id FROM courses WHERE slug = 'real-estate-tools-training';

IF v_course_id IS NULL THEN
  RAISE EXCEPTION 'Course "real-estate-tools-training" not found. Run 05-add-courses.sql first.';
END IF;

-- =============================================
-- MODULE 1: Setting Up Your Digital Workspace
-- =============================================
INSERT INTO course_modules (title, section, description, tier, sort_order, course_id)
VALUES (
  'Setting Up Your Digital Workspace',
  'Digital Foundations',
  'Build a professional, organized digital workspace from day one with the right tools, folder structures, and workflows.',
  'free',
  1,
  v_course_id
) RETURNING id INTO v_mod1;

INSERT INTO course_lessons (id, module_id, title, content, sort_order) VALUES
('ret-1-1', v_mod1, 'Your Technology Stack: What You Need and Why', E'# Your Technology Stack: What You Need and Why\n\nThe right technology stack can save you 10 or more hours per week and make you look more professional to every client you work with. But with hundreds of tools available, many agents either use too few (doing everything manually) or too many (paying for overlapping services they barely use). This lesson helps you build a streamlined, efficient technology stack.\n\n**Essential tools every agent needs:**\n- **Transaction management platform** (dotloop, SkySlope, or similar) — This is your command center for every deal. It stores documents, tracks deadlines, collects signatures, and keeps your broker compliant. If you are not using a transaction management platform, you are creating unnecessary risk and extra work.\n- **Cloud storage** (Google Drive, Dropbox, or OneDrive) — Your filing cabinet for everything that does not live in your transaction platform: marketing materials, listing photos, training documents, personal business files, and templates.\n- **Email and calendar** (Gmail/Google Workspace or Outlook) — Professional email with your own domain looks more credible than a free email address. Calendar integration helps you manage showings, inspections, and closings.\n- **CRM (Customer Relationship Management)** — Follow Up Boss, KVCore, LionDesk, or your brokerage-provided CRM. This is where you track leads, manage follow-ups, and nurture your database.\n- **E-signature tool** — Often built into your transaction platform, but standalone options like DocuSign or Authentisign work too.\n\n**Nice-to-have tools that add value:**\n- Canva for marketing materials\n- ChatGPT or Claude for writing assistance\n- Loom for video messages\n- Calendly for appointment scheduling\n- Slack or Teams for team communication\n\nThe key principle is this: every tool should either save you time, make you money, or reduce your risk. If a tool does not do at least one of those things, you do not need it.', 1),
('ret-1-2', v_mod1, 'Organizing Your Google Drive for Real Estate', E'# Organizing Your Google Drive for Real Estate\n\nGoogle Drive is one of the most powerful free tools available to agents, but most people use it like a junk drawer — files thrown in with no structure, impossible to find anything when you need it. Setting up a proper folder structure takes 30 minutes and saves you hundreds of hours over your career.\n\n**Recommended top-level folder structure:**\n- **01 - Active Transactions** — One subfolder per transaction, named with the property address\n- **02 - Closed Transactions** — Move completed deal folders here for archival\n- **03 - Listings** — Marketing materials, photos, flyers, and listing-specific documents\n- **04 - Buyers** — Buyer agreements, search criteria, showing notes\n- **05 - Marketing** — Templates, social media content, branding materials\n- **06 - Training & Education** — CE certificates, course materials, notes\n- **07 - Business Planning** — Goals, budgets, business plans, tracking sheets\n- **08 - Templates** — Reusable documents, email templates, checklists\n- **09 - Personal** — W-9s, license documents, insurance, tax records\n\n**Inside each transaction folder**, create a consistent subfolder structure:\n- Contract and Amendments\n- Disclosures\n- Inspection Reports\n- Title and Escrow\n- Lender Documents\n- Correspondence\n- Photos\n\n**Naming conventions matter.** Use a consistent format like: YYYY-MM-DD_DocumentName_Address. For example: 2026-02-15_PurchaseAgreement_123MainSt. This makes files sort chronologically and makes searching easy.\n\n**Use Google Drive''s search.** Press the forward slash key (/) to open search, then type keywords. Drive searches file names, contents, and even text within images and PDFs. The better your naming conventions, the faster your searches.\n\n**Share folders, not individual files.** When collaborating with a transaction coordinator, lender, or title company, share the entire transaction folder with appropriate permissions (Viewer or Editor). This gives them access to everything they need without you having to send individual files.', 2),
('ret-1-3', v_mod1, 'Email Management for Busy Agents', E'# Email Management for Busy Agents\n\nReal estate agents receive an enormous volume of email — showing confirmations, MLS alerts, client communications, lender updates, marketing emails, and more. Without a system, important messages get buried and you miss deadlines. Here is how to take control of your inbox.\n\n**Set up labels and filters in Gmail.** Create labels for your key categories: Active Transactions, Leads, Lender Communication, Title/Escrow, Showings, and Marketing. Then create filters that automatically label incoming email based on the sender or subject line. For example, all email from your title company''s domain automatically gets the "Title/Escrow" label. All emails from ShowingTime get the "Showings" label. This keeps your inbox organized without manual effort.\n\n**Use the two-minute rule.** When you check email, if a message can be handled in two minutes or less, handle it immediately. If it requires more time, star it and schedule a specific time to address it. This prevents your inbox from becoming a to-do list that grows faster than you can manage.\n\n**Create email templates for common responses.** Gmail''s template feature (Settings > Advanced > Templates) lets you save pre-written responses that you use frequently. Create templates for: initial buyer inquiry response, listing inquiry response, showing feedback request, offer received notification, under-contract update, and closing congratulations. Templates save 5 to 10 minutes per email and ensure consistent, professional communication.\n\n**Schedule send for strategic timing.** If you are working at 11 PM, your clients do not need to know that. Use Gmail''s schedule send feature to queue emails for the next business morning. Similarly, sending a follow-up email at 8 AM on Tuesday often gets better response rates than sending it at 4 PM on Friday.\n\n**Unsubscribe ruthlessly.** Every marketing email you receive that you never read wastes a few seconds of your attention. Over a year, those seconds add up to hours. Spend 15 minutes unsubscribing from every newsletter, promotional email, and notification you do not actively read. Your future self will thank you.', 3);

INSERT INTO course_quizzes (module_id, question, options, correct_index, sort_order) VALUES
(v_mod1, 'What is the primary purpose of a transaction management platform like dotloop?', '["Social media marketing", "Storing and managing deal documents, tracking deadlines, and collecting signatures", "Generating leads from online advertising", "Creating virtual home tours"]', 1, 1),
(v_mod1, 'What is the recommended naming convention for files in Google Drive?', '["Use random numbers for security", "YYYY-MM-DD_DocumentName_Address format", "Client last name only", "No naming convention is needed if you use search"]', 1, 2),
(v_mod1, 'What does the two-minute rule for email management state?', '["Check email only every two minutes", "Respond to all emails within two minutes of receiving them", "If a message can be handled in two minutes or less handle it immediately", "Delete emails that are more than two days old"]', 2, 3),
(v_mod1, 'Why should you share transaction folders rather than individual files?', '["It uses less storage space", "It gives collaborators access to everything they need without sending individual files", "Individual file sharing is not possible in Google Drive", "Folders download faster than individual files"]', 1, 4),
(v_mod1, 'What is the key principle for evaluating whether you need a technology tool?', '["It should be the newest tool available", "It should save you time, make you money, or reduce your risk", "It should be recommended by at least three other agents", "It should be free"]', 1, 5);


-- =============================================
-- MODULE 2: Mastering dotloop for Transactions
-- =============================================
INSERT INTO course_modules (title, section, description, tier, sort_order, course_id)
VALUES (
  'Mastering dotloop for Transactions',
  'Transaction Management',
  'Learn to use dotloop like a power user — from creating loops and adding documents to collecting signatures and managing compliance.',
  'free',
  2,
  v_course_id
) RETURNING id INTO v_mod2;

INSERT INTO course_lessons (id, module_id, title, content, sort_order) VALUES
('ret-2-1', v_mod2, 'Getting Started with dotloop', E'# Getting Started with dotloop\n\ndotloop is one of the most widely used transaction management platforms in real estate, and for good reason — it combines document storage, e-signatures, and compliance tracking in one platform. Whether your brokerage requires dotloop or you are choosing it independently, mastering this tool will streamline every transaction you handle.\n\n**Setting up your profile.** Before you create your first loop, complete your profile setup. Add your license number, brokerage information, contact details, and a professional photo. This information auto-populates on documents and gives your transactions a professional appearance. Also set up your signature — dotloop lets you create a digital signature that will be applied consistently across all documents you sign.\n\n**Understanding loops.** A "loop" is dotloop''s term for a transaction workspace. Each deal gets its own loop, which contains all the documents, signatures, and activity related to that transaction. Think of a loop as a digital file folder for a specific deal. You can create loops for listings, purchases, leases, or any other type of transaction.\n\n**Creating a new loop.** Click "Create a Loop" and enter the property address. dotloop will auto-populate some property details. Then add the transaction type (purchase, listing, lease), the parties involved (buyers, sellers, agents, lenders, title company), and any relevant dates. Adding all parties upfront means they can be easily added as signers to documents later.\n\n**Adding people to a loop.** You can add anyone involved in the transaction — the other agent, the lender, the title closer, your transaction coordinator, even the client''s attorney. Each person gets a role designation that controls what they can see and do within the loop. Be thoughtful about permissions — your client does not need to see every internal document, and the other agent does not need access to your internal notes.\n\n**Loop status tracking.** dotloop tracks the status of each loop through its lifecycle: Draft, Active, Under Contract, Closed, or Archived. Update the status as the transaction progresses. This gives your broker a real-time view of your pipeline and helps you stay organized across multiple active deals.', 1),
('ret-2-2', v_mod2, 'Documents and E-Signatures in dotloop', E'# Documents and E-Signatures in dotloop\n\nThe core of dotloop''s value is its document management and e-signature workflow. Getting documents signed quickly and correctly is essential to keeping deals on track.\n\n**Uploading documents.** You can add documents to a loop in several ways: upload from your computer, use dotloop''s built-in template library (which includes standard forms for many states and associations), import from Google Drive or Dropbox, or take a photo with the mobile app. When uploading, give each document a clear, descriptive name — "Purchase Agreement" is better than "Document1.pdf".\n\n**Using templates.** If your brokerage or association has loaded templates into dotloop, you can pull standard forms directly into your loop. These templates often include auto-fill fields that populate with information from the loop (property address, buyer name, seller name, etc.), saving you from typing the same information repeatedly.\n\n**Setting up signature fields.** Before requesting signatures, you need to place signature fields on the document. Open the document in dotloop''s editor and drag signature fields, initial fields, date fields, and text fields to the appropriate locations. Assign each field to the correct signer. Take your time here — incorrectly placed fields cause confusion and delays.\n\n**Requesting signatures.** Once your fields are placed, click "Request Signatures" and select the signers in the order you want them to sign. dotloop sends an email notification to each signer with a link to review and sign the document. You can track who has signed and who has not, and send reminders to those who have not yet completed their signatures.\n\n**Signing on mobile.** dotloop''s mobile app allows signers to review and sign documents from their phone or tablet. This is especially useful for clients who are not near a computer. The mobile signing experience is designed to be simple — signers tap where they need to sign and can complete the process in minutes.\n\n**Managing revisions.** If a document needs to be revised after signatures have been collected (for example, an amendment to the purchase agreement), you can upload the revised document and request new signatures. dotloop maintains a version history so you can always access the original signed version.', 2),
('ret-2-3', v_mod2, 'Advanced dotloop Features and Compliance', E'# Advanced dotloop Features and Compliance\n\nOnce you are comfortable with the basics, these advanced features will help you work faster and keep your broker happy.\n\n**Task lists and deadlines.** dotloop allows you to create task lists within each loop — inspection deadline, appraisal deadline, financing contingency date, closing date, and any other milestones. You can set reminders that notify you (and optionally other parties) as deadlines approach. Never miss a contingency date again.\n\n**Loop templates.** If you use the same document set for most transactions, create a loop template. A template pre-loads specific documents, task lists, and even form fields into every new loop you create from that template. For example, your "Standard Purchase" template might include the purchase agreement, disclosure forms, lead-based paint disclosure, agency disclosure, and your standard task list. This saves 15 to 20 minutes per transaction setup.\n\n**Compliance review.** Many brokerages use dotloop''s compliance features to review transactions. When you submit a loop for review, your broker or compliance officer can check that all required documents are present, properly signed, and complete. If something is missing, they can flag it and send it back to you. Understanding your brokerage''s compliance requirements in dotloop saves back-and-forth and gets your deals approved faster.\n\n**Sharing loops with external parties.** You can share a read-only or edit-access link to a loop with anyone, even if they do not have a dotloop account. This is useful for sharing documents with attorneys, inspectors, or other parties who need access to specific documents but do not need full loop participation.\n\n**Reporting and analytics.** dotloop provides transaction reporting that shows your volume, average time to close, and document completion rates. Use this data to identify bottlenecks in your process. If your average time from offer to closing is 45 days but the market average is 35 days, investigate where the delays are occurring — is it document collection, inspections, or lender timelines?\n\n**Integration with other tools.** dotloop integrates with many CRMs and transaction platforms. If your CRM can push contact data to dotloop, or if dotloop can push closed transaction data to your CRM, set up those integrations to eliminate double data entry.', 3);

INSERT INTO course_quizzes (module_id, question, options, correct_index, sort_order) VALUES
(v_mod2, 'What is a "loop" in dotloop?', '["A recurring email reminder", "A transaction workspace containing all documents and activity for a specific deal", "A type of digital signature", "A marketing campaign workflow"]', 1, 1),
(v_mod2, 'What should you do BEFORE requesting signatures on a document in dotloop?', '["Print the document and mail it", "Place signature fields, initial fields, and date fields in the correct locations", "Send the document to your broker for pre-approval", "Convert the document to a spreadsheet"]', 1, 2),
(v_mod2, 'What is the benefit of creating loop templates in dotloop?', '["Templates make documents legally binding", "They pre-load documents and task lists saving 15 to 20 minutes per transaction setup", "Templates are required by most brokerages", "They automatically fill in the sale price"]', 1, 3),
(v_mod2, 'How does dotloop help with compliance?', '["It automatically reports all transactions to the IRS", "Brokers can review loops to check that required documents are present and properly signed", "It prevents agents from making any mistakes", "Compliance features are only available to brokers"]', 1, 4),
(v_mod2, 'What information should you set up in your dotloop profile before creating your first loop?', '["Only your name is needed", "License number, brokerage info, contact details, photo, and digital signature", "Social security number and bank account", "Just your email address"]', 1, 5);


-- =============================================
-- MODULE 3: CRM Fundamentals for Agents
-- =============================================
INSERT INTO course_modules (title, section, description, tier, sort_order, course_id)
VALUES (
  'CRM Fundamentals for Agents',
  'CRM and Database',
  'Set up and use your CRM effectively to track leads, manage follow-ups, and build a database that generates repeat and referral business.',
  'premium',
  3,
  v_course_id
) RETURNING id INTO v_mod3;

INSERT INTO course_lessons (id, module_id, title, content, sort_order) VALUES
('ret-3-1', v_mod3, 'Why Your CRM Is Your Most Valuable Business Asset', E'# Why Your CRM Is Your Most Valuable Business Asset\n\nYour CRM is not just a contact list — it is the engine that drives your business. The agents who consistently earn six figures and beyond are almost always the ones who use their CRM religiously. Here is why it matters and how to think about it.\n\n**Your database is your business.** When you leave a brokerage, you take your relationships with you (subject to your contract). Your CRM is where those relationships live in organized, actionable form. Every contact, every note, every follow-up reminder, every transaction history entry is part of your business asset. Treat it that way.\n\n**The fortune is in the follow-up.** Industry data consistently shows that most real estate sales come from the agent''s sphere of influence — past clients, friends, family, and referrals. But these sales only happen if you stay in touch. A CRM makes systematic follow-up possible. Without one, you are relying on memory, sticky notes, and good intentions — and business falls through the cracks.\n\n**CRM options for agents:**\n- **Follow Up Boss** — Popular among teams and high-producing agents. Strong lead routing, calling features, and integration with lead sources.\n- **KVCore** — Often included with brokerage platforms. Comprehensive marketing and lead management features.\n- **LionDesk** — Affordable option with video email, texting, and drip campaign features.\n- **Wise Agent** — Budget-friendly with good transaction management integration.\n- **Your brokerage CRM** — Many brokerages provide a CRM at no additional cost. Use it if it meets your needs.\n\nThe best CRM is the one you will actually use. A sophisticated platform that you ignore is worth less than a simple one you use every day. Start with whatever your brokerage provides, learn to use it well, and upgrade only when you have outgrown its capabilities.\n\n**The minimum viable CRM habit:** Every person you interact with professionally gets entered into your CRM within 24 hours, with a follow-up reminder set. That one habit, practiced consistently, will transform your business over 12 to 24 months.', 1),
('ret-3-2', v_mod3, 'Setting Up Your CRM for Success', E'# Setting Up Your CRM for Success\n\nA CRM is only as good as the data you put into it and the systems you build around it. Spend time setting it up properly and you will save countless hours later.\n\n**Contact categories and tags.** Organize your contacts into categories that match how you interact with them. Common categories include: Past Clients (buyers and sellers you have closed with), Active Clients (currently in a transaction), Hot Leads (actively looking to buy or sell within 90 days), Warm Leads (interested but 6 to 12 months out), Sphere of Influence (friends, family, and professional contacts who send you referrals), Vendors (lenders, inspectors, title companies, photographers), and Agents (co-op agents you work with regularly). Tag contacts with additional labels like "investor," "first-time buyer," "relocation," or "luxury" to enable targeted communication.\n\n**Essential information to capture for every contact:**\n- Full name and preferred name\n- Phone number and email address\n- Physical address\n- Lead source (how they found you)\n- Category and tags\n- Key dates (birthday, home anniversary, closing anniversary)\n- Property preferences (if they are a buyer)\n- Notes from every conversation\n\n**Set up automated follow-up sequences.** Most CRMs allow you to create drip campaigns — automated email or text sequences triggered by specific events. Essential sequences include: New Lead (immediate response plus 7-day follow-up series), Post-Closing (30-day, 90-day, 6-month, and annual check-ins), Anniversary (annual closing anniversary message), and Birthday (automated birthday greeting). These sequences ensure no contact falls through the cracks even during your busiest months.\n\n**Daily CRM routine.** Block 15 to 30 minutes every morning for CRM tasks: review today''s follow-up reminders, log notes from yesterday''s conversations, add any new contacts, and check which drip campaigns need attention. This small daily investment keeps your database clean and your pipeline full.', 2),
('ret-3-3', v_mod3, 'Turning Your Database Into Transactions', E'# Turning Your Database Into Transactions\n\nHaving a well-organized CRM is the foundation. Turning that database into consistent transactions is the goal. Here are the strategies that convert contacts into closings.\n\n**The 33-Touch System.** This classic approach involves contacting every person in your sphere of influence 33 times per year through a mix of channels: monthly email newsletters, quarterly phone calls, annual in-person visits, birthday and anniversary messages, market update mailings, social media engagement, and community event invitations. The idea is to stay consistently top-of-mind so that when someone in your network (or someone they know) thinks about real estate, you are the first agent they think of.\n\n**Segment your outreach.** Not every contact needs the same level of attention. Your top 50 contacts — past clients, top referral sources, and close friends — should get personal phone calls quarterly. Your next 150 contacts get monthly email plus occasional personal touches. The rest of your database gets your monthly newsletter and automated sequences. This tiered approach focuses your limited time on the contacts most likely to generate business.\n\n**Provide value in every touch.** Nobody wants to receive 33 sales pitches per year. Your touches should provide genuine value: a neighborhood market update, a home maintenance tip, a local restaurant recommendation, a just-sold announcement, or an invitation to a client appreciation event. When you consistently provide value, people welcome your communication instead of ignoring it.\n\n**Track your metrics.** Your CRM should tell you: how many new contacts you added this month, how many follow-ups you completed, how many conversations you had, how many appointments you set, and how many transactions resulted from database contacts. Track these numbers monthly and look for trends. If your contact-to-appointment ratio drops, your messaging may need refreshing. If your appointments-to-closings ratio drops, your consultation skills may need work.\n\n**Ask for referrals systematically.** Do not wait for referrals to come to you — actively ask for them at specific points: after providing exceptional service, at closing, during your annual check-in, and when a past client comments positively about their experience. Script it naturally: "I am so glad we were able to get this done for you. If you know anyone else thinking about buying or selling, I would love the opportunity to help them the same way." Most agents never ask, and it costs them thousands of dollars in lost referral business every year.', 3);

INSERT INTO course_quizzes (module_id, question, options, correct_index, sort_order) VALUES
(v_mod3, 'What is the minimum viable CRM habit every agent should practice?', '["Send a monthly newsletter to your entire database", "Enter every professional contact into your CRM within 24 hours with a follow-up reminder", "Call every contact in your database every week", "Post on social media three times per day"]', 1, 1),
(v_mod3, 'What does the 33-Touch System involve?', '["Sending 33 emails in one day to a new lead", "Contacting every person in your sphere 33 times per year through a mix of channels", "Having 33 active transactions at all times", "Making 33 cold calls every morning"]', 1, 2),
(v_mod3, 'Why should you segment your outreach by contact tier?', '["To save money on postage", "To focus your limited time on contacts most likely to generate business", "Because your CRM requires segmentation", "To comply with email marketing regulations"]', 1, 3),
(v_mod3, 'What is the most important type of content to provide in your database touches?', '["Sales pitches and listing promotions", "Requests for referrals", "Genuine value such as market updates, tips, and local recommendations", "Links to your social media profiles"]', 2, 4),
(v_mod3, 'When is the best time to ask a past client for a referral?', '["Only when you need business", "At specific points like after exceptional service, at closing, and during annual check-ins", "Never — referrals should come naturally", "Only by email, never in person"]', 1, 5);


-- =============================================
-- MODULE 4: Digital Marketing Tools
-- =============================================
INSERT INTO course_modules (title, section, description, tier, sort_order, course_id)
VALUES (
  'Digital Marketing Tools for Agents',
  'Marketing Tools',
  'Master the design and marketing tools that help you create professional listing materials, social media content, and client communications.',
  'premium',
  4,
  v_course_id
) RETURNING id INTO v_mod4;

INSERT INTO course_lessons (id, module_id, title, content, sort_order) VALUES
('ret-4-1', v_mod4, 'Creating Professional Marketing Materials with Canva', E'# Creating Professional Marketing Materials with Canva\n\nYou do not need to be a graphic designer to create stunning marketing materials. Canva has become the go-to design tool for real estate agents, and for good reason — it is intuitive, affordable, and produces professional results. Here is how to use it effectively.\n\n**Setting up your brand kit.** Before you create anything, set up your brand kit in Canva. Add your brand colors (use the hex codes from your brokerage or personal brand guide), upload your logo, and select your brand fonts. Once saved, these elements are available in every design you create, ensuring consistent branding across all your materials.\n\n**Essential templates for agents:**\n- **Just Listed / Just Sold flyers** — Single-page flyers with property photos, key features, and your contact information. Create one template and reuse it for every listing.\n- **Open House invitations** — Both digital (for email and social media) and print-ready versions.\n- **Social media posts** — Square (1080x1080) for Instagram, landscape (1200x630) for Facebook, vertical (1080x1920) for Stories and Reels.\n- **Market update graphics** — Monthly or quarterly market stats presented in a visually appealing format.\n- **Listing presentations** — A polished slide deck you can customize for each listing appointment.\n- **Buyer guides** — A multi-page digital guide that walks buyers through the purchase process.\n- **Closing gifts cards** — Personalized thank-you cards to accompany closing gifts.\n\n**Photo editing basics.** Canva includes basic photo editing tools that can enhance your listing photos: brightness and contrast adjustments, cropping, and filters. For more professional editing, use a dedicated tool like Lightroom or hire a professional photographer. But for social media posts and flyers, Canva''s built-in editing is usually sufficient.\n\n**Batch creating content.** One of Canva''s biggest time-savers is the ability to duplicate and modify designs quickly. Create one "Just Listed" post, then duplicate it and swap out the photo, address, and details for the next listing. You can create a month''s worth of social media content in a single focused session.\n\n**Canva Pro vs. Free.** The free version is surprisingly capable, but Canva Pro ($12.99/month) adds valuable features: background removal, brand kit, Magic Resize (instantly resize a design for different platforms), and access to the full photo and element library. For most agents, Pro is worth the investment.', 1),
('ret-4-2', v_mod4, 'Social Media Strategy and Scheduling', E'# Social Media Strategy and Scheduling\n\nSocial media is where your sphere of influence spends their time, which makes it one of the most cost-effective marketing channels for real estate agents. But posting randomly without a strategy wastes time and produces mediocre results. Here is how to approach social media strategically.\n\n**Choose your platforms wisely.** You do not need to be on every platform. Focus on 2 to 3 where your target audience is most active. For most residential agents, this means: **Instagram** (visual platform, great for showcasing properties and lifestyle), **Facebook** (largest audience, best for community engagement and groups), and **LinkedIn** (professional networking, good for referral relationships). If you have the bandwidth, add YouTube for video content or TikTok for reaching younger demographics.\n\n**Content pillars.** Organize your content around 4 to 5 recurring themes (pillars) that represent different aspects of your brand. Example pillars for a real estate agent: (1) Property Showcases — listings, virtual tours, neighborhood highlights. (2) Market Insights — local market data, trends, predictions. (3) Behind the Scenes — day-in-the-life content, transaction milestones. (4) Education — tips for buyers and sellers, home maintenance advice. (5) Community — local events, restaurant recommendations, neighborhood spotlights. Rotating through these pillars keeps your content varied and prevents you from posting only sales content.\n\n**Posting frequency.** Quality matters more than quantity. Aim for 3 to 5 posts per week on your primary platform. Posting once a day is ideal if you can maintain quality. Stories and Reels can be more frequent and casual — 1 to 3 per day is a good target.\n\n**Scheduling tools.** Do not try to post in real time every day — you will miss days and lose consistency. Use a scheduling tool to batch-create and schedule content in advance. **Later**, **Buffer**, and **Hootsuite** are popular options. Meta Business Suite (free) handles Facebook and Instagram scheduling. Schedule a week or month of content in one sitting, then add spontaneous posts as timely content arises.\n\n**Engagement is not optional.** Posting content without engaging with your audience is like throwing a party and hiding in the kitchen. Respond to every comment, reply to DMs promptly, comment on other people''s posts, and participate in local community groups. The algorithm rewards engagement, and so do your future clients.', 2),
('ret-4-3', v_mod4, 'Video Tools and Virtual Tour Technology', E'# Video Tools and Virtual Tour Technology\n\nVideo content gets more engagement, builds more trust, and generates more leads than any other content type. Yet most agents avoid video because they find it intimidating. The good news: you do not need expensive equipment or professional editing skills to create effective real estate video content.\n\n**Essential video types for agents:**\n- **Property walkthrough videos** — A 60 to 90 second walkthrough of a listing, narrated by you. Post on social media, YouTube, and embed in your MLS listing.\n- **Neighborhood tours** — Drive or walk through a neighborhood highlighting amenities, parks, schools, and local businesses. Great evergreen content.\n- **Market update videos** — A 2 to 3 minute video sharing monthly market stats and your analysis. Establishes you as a market expert.\n- **Client testimonials** — Ask happy clients to record a 30-second video testimonial after closing. Video testimonials are far more persuasive than written reviews.\n- **Educational content** — Short videos explaining the buying or selling process, common questions, or tips.\n\n**Equipment you actually need:**\n- A smartphone with a good camera (any phone made in the last 3 years is fine)\n- A gimbal or stabilizer ($80 to $150 — makes your walkthrough videos smooth instead of shaky)\n- A wireless microphone ($30 to $60 — audio quality matters more than video quality)\n- A ring light for indoor or talking-head videos ($25 to $50)\n- A tripod for stationary shots ($20 to $40)\n\nTotal investment: under $300 for a professional-quality setup.\n\n**Editing tools:**\n- **CapCut** (free) — Excellent mobile video editor with templates, captions, and effects. Perfect for social media content.\n- **iMovie** (free on Apple devices) — Simple desktop editor for longer videos.\n- **Loom** — Screen recording tool perfect for creating quick video messages for clients or training content.\n- **Canva Video** — Create animated social media videos using templates.\n\n**Virtual tour platforms.** For immersive 3D tours, **Matterport** is the industry standard but requires a special camera ($300+). **Zillow 3D Home** offers a free alternative using just your iPhone. **CloudPano** and **EyeSpy360** are budget-friendly options. For most listings, a well-shot video walkthrough performs just as well as a 3D tour and takes a fraction of the time to produce.', 3);

INSERT INTO course_quizzes (module_id, question, options, correct_index, sort_order) VALUES
(v_mod4, 'What should you set up in Canva BEFORE creating any marketing materials?', '["A subscription to Canva Pro", "Your brand kit with colors, logo, and fonts", "A social media account connected to Canva", "At least 50 stock photos"]', 1, 1),
(v_mod4, 'How many content pillars should an agent typically organize their social media around?', '["1 to 2", "4 to 5", "8 to 10", "As many as possible"]', 1, 2),
(v_mod4, 'What is more important than video quality when creating real estate videos?', '["Video length", "Audio quality", "Special effects", "The editing software used"]', 1, 3),
(v_mod4, 'What is the recommended posting frequency for an agents primary social media platform?', '["Once a month", "3 to 5 posts per week", "10 posts per day", "Only when you have a new listing"]', 1, 4),
(v_mod4, 'Why should agents use social media scheduling tools?', '["Scheduling tools make posts go viral", "They allow batch-creating content in advance maintaining consistency without daily effort", "They are required by most brokerages", "They automatically generate content for you"]', 1, 5);


-- =============================================
-- MODULE 5: Transaction Coordination Tools
-- =============================================
INSERT INTO course_modules (title, section, description, tier, sort_order, course_id)
VALUES (
  'Transaction Coordination Tools',
  'Transaction Workflows',
  'Streamline your transaction process from contract to closing with the right tools, checklists, and workflow automations.',
  'premium',
  5,
  v_course_id
) RETURNING id INTO v_mod5;

INSERT INTO course_lessons (id, module_id, title, content, sort_order) VALUES
('ret-5-1', v_mod5, 'Building Your Transaction Checklist System', E'# Building Your Transaction Checklist System\n\nA missed deadline can kill a deal. A forgotten document can delay closing. A dropped follow-up can cost you a client. The solution is a comprehensive checklist system that you follow for every transaction — no exceptions.\n\n**Why checklists work.** Research in fields from aviation to surgery shows that checklists reduce errors dramatically, even for experienced professionals. In real estate, the average transaction involves 20 to 30 distinct tasks, 10 to 15 documents, and coordination with 5 to 10 different parties. No one can reliably track all of that in their head, especially when managing multiple transactions simultaneously.\n\n**Create separate checklists for each transaction type:**\n- Buyer-side purchase (standard)\n- Buyer-side purchase (new construction)\n- Buyer-side purchase (foreclosure/REO)\n- Listing (standard)\n- Listing (short sale)\n- Listing (estate/probate)\n- Lease transaction\n\nEach checklist should include every task from contract acceptance to closing and beyond, organized chronologically.\n\n**Essential checklist items for a standard buyer transaction:**\n- Executed purchase agreement distributed to all parties\n- Earnest money deposited within the contractual timeframe\n- Title company opened and title work ordered\n- Home inspection scheduled and completed\n- Inspection response delivered within the contingency period\n- Appraisal ordered by the lender\n- Appraisal completed and reviewed\n- Survey ordered (if required)\n- HOA documents requested and reviewed\n- Final loan approval (clear to close) received\n- Closing disclosure reviewed by buyer\n- Final walkthrough scheduled and completed\n- Closing date confirmed with all parties\n- Utilities transferred to buyer\n- Post-closing follow-up with client\n\n**Where to store your checklists.** You can build checklists in several places: your transaction management platform (dotloop has task lists), a project management tool like Trello or Asana, a Google Sheet, or even a simple Google Doc. The key is that the checklist is accessible, updatable, and integrated into your daily workflow. If you have to go looking for it, you will not use it.', 1),
('ret-5-2', v_mod5, 'Communication Workflows for Active Transactions', E'# Communication Workflows for Active Transactions\n\nKeeping all parties informed during a transaction is one of the most time-consuming — and most important — parts of an agent''s job. A communication workflow ensures that everyone gets the right information at the right time without you having to write individual updates from scratch.\n\n**Identify your communication touchpoints.** At minimum, the following events should trigger a client update: offer accepted, earnest money deposited, inspection scheduled, inspection completed (with summary), inspection response accepted, appraisal scheduled, appraisal results, clear to close received, closing date and time confirmed, and post-closing follow-up. Map out every communication touchpoint for your transaction type and create a template for each one.\n\n**Email templates for common updates.** Draft a template for each touchpoint that you can customize in 2 to 3 minutes. For example, your "Inspection Completed" template might read: "Hi [Client Name], the home inspection for [Property Address] has been completed. The inspector found [summary of findings]. I have attached the full report for your review. I recommend we discuss the findings and determine our response strategy. Are you available for a quick call [tomorrow/this afternoon]? We have until [date] to submit our inspection response." Save these templates in your email client or CRM for quick access.\n\n**Weekly status updates.** During active transactions, send a brief weekly status update to your client every Friday. Cover what happened this week, what is coming up next week, and any action items the client needs to handle. This proactive communication dramatically reduces anxious client calls and builds trust. Even if nothing significant happened during the week, let them know: "Everything is progressing smoothly this week. The lender is processing the loan and we are on track for our closing date of March 15th."\n\n**Coordinating with other parties.** Create a standard email you send to the other agent, lender, and title company at key milestones. When an inspection response is agreed upon, for example, send a brief email to the lender and title company: "FYI — inspection response has been fully executed. No changes to the contract price. Attached for your records." This keeps everyone in the loop without lengthy phone calls.\n\n**Use group text threads strategically.** For fast-moving transactions or time-sensitive items, a group text thread with your client can be more effective than email. Set expectations upfront about what you will communicate via text (urgent items, scheduling) versus email (documents, detailed updates).', 2),
('ret-5-3', v_mod5, 'Deadline Tracking and Calendar Management', E'# Deadline Tracking and Calendar Management\n\nMissing a contractual deadline is one of the most dangerous mistakes an agent can make. It can void a contract, expose you to liability, and destroy a client relationship. Effective deadline tracking requires both a system and a habit.\n\n**Critical deadlines in every transaction:**\n- Earnest money deposit deadline\n- Option period or inspection contingency expiration\n- Financing contingency deadline\n- Appraisal contingency deadline\n- Title objection deadline\n- Survey delivery deadline\n- HOA document review period\n- Final walkthrough window\n- Closing date\n- Post-closing possession deadlines\n\nEvery one of these deadlines should be in your calendar the moment the contract is executed. Do not wait until the week before to check your dates.\n\n**Calendar management best practices:**\n- Use a **dedicated calendar** (in Google Calendar or Outlook) for transaction deadlines, separate from your personal and showing calendars. Color-code it so deadlines stand out visually.\n- Set **multiple reminders** for critical deadlines: 7 days before, 3 days before, and 1 day before. For the most critical deadlines (inspection contingency, financing contingency), add a 2-week advance reminder so you can take action before the deadline arrives.\n- Block time on your calendar for deadline-related tasks. If the inspection contingency expires on March 10th, block time on March 3rd to schedule the inspection and on March 8th to prepare the inspection response.\n\n**Technology tools for deadline tracking:**\n- **dotloop task lists** — Built into your transaction platform with reminders.\n- **Google Calendar** — Simple, reliable, and syncs across all devices. Create a specific calendar called "Transaction Deadlines."\n- **Trello or Asana** — Visual project management tools where you can create a board for each transaction with cards for each deadline.\n- **SkySlope** — Another popular transaction management platform with built-in deadline tracking.\n- **ListedKit** — Purpose-built for real estate transaction management with automated deadline calculation.\n\n**The daily deadline review.** Every morning, as part of your CRM routine, review your transaction deadline calendar for the next 7 days. Identify any deadlines approaching and the actions needed to meet them. This 5-minute daily review prevents surprises and keeps every transaction on track.', 3);

INSERT INTO course_quizzes (module_id, question, options, correct_index, sort_order) VALUES
(v_mod5, 'Why are checklists important for real estate transactions?', '["They are required by law in all states", "They reduce errors in a process that involves 20 to 30 tasks and 10 to 15 documents", "They replace the need for a transaction coordinator", "They automatically complete tasks for you"]', 1, 1),
(v_mod5, 'How often should you send status updates to clients during an active transaction?', '["Only when something goes wrong", "Weekly on Friday", "Every hour during business hours", "Only when the client asks for an update"]', 1, 2),
(v_mod5, 'When should transaction deadlines be entered into your calendar?', '["The week before each deadline", "The moment the contract is executed", "Only for the closing date", "When the lender requests them"]', 1, 3),
(v_mod5, 'How many reminders should be set for critical contract deadlines?', '["One reminder the day before", "Multiple reminders at 7 days, 3 days, and 1 day before", "No reminders are needed if you use a checklist", "One reminder one month before"]', 1, 4),
(v_mod5, 'What should a weekly client status update include?', '["Only the closing date", "What happened this week, what is coming next week, and any client action items", "A request for a referral", "A detailed legal analysis of the contract"]', 1, 5);


-- =============================================
-- MODULE 6: Productivity and Automation
-- =============================================
INSERT INTO course_modules (title, section, description, tier, sort_order, course_id)
VALUES (
  'Productivity and Automation for Agents',
  'Productivity Systems',
  'Leverage automation tools and productivity systems to work smarter, serve more clients, and reclaim hours in your week.',
  'premium',
  6,
  v_course_id
) RETURNING id INTO v_mod6;

INSERT INTO course_lessons (id, module_id, title, content, sort_order) VALUES
('ret-6-1', v_mod6, 'Time Blocking and Task Management', E'# Time Blocking and Task Management\n\nReal estate agents face a unique productivity challenge: the work is highly varied, largely self-directed, and constantly interrupted by client calls, showing requests, and urgent deal issues. Without a time management system, most agents spend their days reacting instead of producing. Time blocking is the solution.\n\n**How time blocking works.** Instead of maintaining a to-do list and trying to fit tasks into random gaps in your day, you assign specific blocks of time to specific types of work. Your calendar becomes your to-do list. When something is on the calendar, it gets done. When it is just on a list, it competes with everything else for your attention.\n\n**Recommended time blocks for agents:**\n- **Lead generation (1 to 2 hours daily)** — Calls, follow-ups, prospecting, social media outreach. Schedule this first thing in the morning when your energy and focus are highest. Protect this block fiercely — it is the activity that directly generates income.\n- **Client meetings and showings (2 to 4 hours daily)** — Listing appointments, buyer consultations, showings. Group these in the late morning or afternoon when clients are typically available.\n- **Administrative (1 to 2 hours daily)** — Email, paperwork, transaction management, CRM updates. Batch these tasks into a single block rather than doing them throughout the day.\n- **Education and development (30 minutes daily or 2 hours weekly)** — Training, market research, skill development. Agents who invest in their own development outperform those who do not.\n- **Personal time (protected)** — Block personal time just as you block work time. Burnout is the biggest threat to a sustainable real estate career.\n\n**Task management tools.** Beyond your calendar, you need a task management system for the items that do not fit neatly into time blocks. **Todoist** (free and paid versions) is simple and effective. **Google Tasks** integrates directly with Gmail and Calendar. **Notion** is more flexible but has a steeper learning curve. **Asana** is excellent for teams. The key, again, is using whatever tool you will actually use consistently.\n\n**The power of batching.** Group similar tasks together to reduce context switching. Return all phone calls in one block. Write all social media posts in one session. Process all emails in two or three daily batches rather than constantly checking. Every time you switch between tasks, you lose 15 to 25 minutes of productive focus. Batching minimizes these switches and dramatically increases your output.', 1),
('ret-6-2', v_mod6, 'Automating Repetitive Tasks', E'# Automating Repetitive Tasks\n\nAutomation is not about replacing the personal touch that makes great agents successful — it is about eliminating the repetitive mechanical tasks that consume your time so you can spend more time on the high-value activities that require your expertise and personality.\n\n**Email automations.** Set up automated email sequences for common scenarios: new lead response (immediate), showing follow-up (same day), post-closing drip (30, 60, 90 days, then annually), birthday greetings, and home anniversary messages. Most CRMs include automation features, and tools like Mailchimp or Constant Contact can supplement your CRM''s capabilities.\n\n**Text message automations.** Services like EZTexting or your CRM''s built-in texting feature can send automated text messages for appointment reminders, showing confirmations, and brief check-ins. A text message reminding a buyer about tomorrow''s showing at 10 AM saves you a phone call and reduces no-shows.\n\n**Social media automation.** Schedule posts in advance using Later, Buffer, or Meta Business Suite. Create a content calendar, batch-produce your content monthly, and schedule it to post automatically. You still need to engage with comments and messages personally, but the posting itself can be automated.\n\n**Document automation.** Use dotloop templates and pre-filled forms to reduce manual data entry. Some agents use tools like Jotform or Google Forms to collect buyer and seller information digitally before their first meeting, then auto-populate that data into their CRM and transaction documents.\n\n**Zapier and Make (formerly Integromat)** are powerful automation platforms that connect different tools. Examples: when a lead fills out a form on your website, Zapier can automatically add them to your CRM, send them a welcome email, notify you via text, and create a task in your task manager — all without you lifting a finger. When a transaction closes in dotloop, Zapier can add the client to your post-closing drip campaign in your email platform.\n\n**Start simple.** Do not try to automate everything at once. Identify the three tasks you repeat most often, automate those first, and add more automations as you get comfortable. Even automating just your new lead response and post-closing follow-up will save you hours every month.', 2),
('ret-6-3', v_mod6, 'Building Systems That Scale', E'# Building Systems That Scale\n\nThe difference between an agent who earns $100,000 and one who earns $500,000 is rarely talent — it is systems. Scalable systems allow you to serve more clients at a higher level without proportionally increasing your time investment.\n\n**Document your processes.** Every repeatable process in your business should be documented in a step-by-step checklist or standard operating procedure (SOP). How do you onboard a new buyer client? What happens when a listing goes live? How do you prepare for a closing? Write it down. This documentation serves two purposes: it ensures consistency in your own work, and it allows you to delegate tasks to an assistant, transaction coordinator, or team member in the future.\n\n**Create a business operations manual.** Store all your SOPs in one location — a Google Drive folder, a Notion workspace, or a simple binder. Include sections for: lead management, buyer process, seller process, transaction management, marketing, and administration. This manual becomes the playbook for your business and is invaluable when you are ready to hire help.\n\n**When to hire help.** The general rule is: if a task does not require your license, your expertise, or your personal relationship, someone else should be doing it. Transaction coordinators ($300 to $500 per transaction) handle paperwork, deadline tracking, and communication with title and lender. Virtual assistants ($15 to $25 per hour) can manage your CRM, schedule social media, confirm appointments, and handle data entry. A showing assistant (licensed) can cover showings when you are unavailable. Start by calculating your effective hourly rate: if you earn $200,000 and work 2,000 hours, your time is worth $100 per hour. Any task you can delegate for less than $100 per hour gives you a positive return.\n\n**Measure what matters.** Track the key metrics that drive your business: leads generated per week, appointments set per week, contracts written per month, closings per month, average commission, and total GCI (Gross Commission Income). Review these numbers monthly and look for the bottleneck — the metric that, if improved, would have the biggest impact on your income. Then focus your improvement efforts on that bottleneck.\n\n**Continuous improvement.** Every quarter, review your systems and ask: What is taking too long? What falls through the cracks? What do clients complain about? What do I dread doing? The answers to these questions reveal where your systems need improvement. Small, incremental improvements compound over time into a dramatically more efficient and profitable business.', 3);

INSERT INTO course_quizzes (module_id, question, options, correct_index, sort_order) VALUES
(v_mod6, 'What is the recommended first time block in an agents daily schedule?', '["Administrative tasks and email", "Lead generation and prospecting", "Social media posting", "Showing properties to buyers"]', 1, 1),
(v_mod6, 'How much productive focus time is lost each time you switch between different types of tasks?', '["1 to 2 minutes", "5 to 10 minutes", "15 to 25 minutes", "No time is lost when switching tasks"]', 2, 2),
(v_mod6, 'What is Zapier used for in a real estate business?', '["Creating virtual tours", "Connecting different tools to automate workflows between them", "Designing marketing materials", "Filing taxes"]', 1, 3),
(v_mod6, 'When should an agent consider hiring a transaction coordinator?', '["Only after closing 100 transactions per year", "When tasks that do not require your license or expertise are consuming your time", "Never — agents should handle everything personally", "Only if the brokerage requires it"]', 1, 4),
(v_mod6, 'What is the purpose of documenting your business processes as SOPs?', '["To satisfy legal requirements", "To ensure consistency in your work and enable future delegation", "To impress clients during listing presentations", "SOPs are only needed for large teams"]', 1, 5);

RAISE NOTICE 'Real Estate Tools Training course content inserted successfully!';
RAISE NOTICE 'Modules: 6, Lessons: 18, Quiz Questions: 30';

END $$;
